# JLPT N3 Practice Questions
# Vocabulary: 30, Grammar: 30, Reading: 15, Listening: 15 = 90 total

N3_VOCAB = [
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "会議の前に資料を（　　）してください。",
        "option_a": "確認",
        "option_b": "感動",
        "option_c": "注目",
        "option_d": "選択",
        "correct_answer": "A",
        "explanation": "「確認」は内容や事実を確かめるという意味です。会議の前に資料を確かめることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "担当者に（　　）を取ってから、訪問してください。",
        "option_a": "判断",
        "option_b": "連絡",
        "option_c": "影響",
        "option_d": "原因",
        "correct_answer": "B",
        "explanation": "「連絡」は情報を伝えたり、相手に知らせたりすることです。訪問前に連絡を取ることが重要です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "新しい機械の使い方を（　　）してもらいました。",
        "option_a": "解決",
        "option_b": "準備",
        "option_c": "説明",
        "option_d": "結果",
        "correct_answer": "C",
        "explanation": "「説明」は物事の内容や意味をわかりやすく伝えることです。機械の使い方を教えてもらった場面に合います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "試験の（　　）を十分にしておかないと、合格できません。",
        "option_a": "機会",
        "option_b": "準備",
        "option_c": "状況",
        "option_d": "判断",
        "correct_answer": "B",
        "explanation": "「準備」は物事を行う前に必要なものをそろえたり、整えたりすることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "この問題は自分で（　　）するのが難しいので、先生に相談しました。",
        "option_a": "判断",
        "option_b": "連絡",
        "option_c": "確認",
        "option_d": "解決",
        "correct_answer": "D",
        "explanation": "「解決」は問題や困難な状況を終わらせることです。問題を終わらせるために先生に相談した文脈に合います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "現在の（　　）を正確に把握することが大切です。",
        "option_a": "状況",
        "option_b": "結果",
        "option_c": "原因",
        "option_d": "機会",
        "correct_answer": "A",
        "explanation": "「状況」は物事が現在どのような状態にあるかを表す言葉です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "この薬は体に（　　）を与える可能性があります。",
        "option_a": "解決",
        "option_b": "影響",
        "option_c": "判断",
        "option_d": "説明",
        "correct_answer": "B",
        "explanation": "「影響」は他のものに何らかの変化や作用を与えることです。薬が体に変化を与える文脈に合います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "火事の（　　）は、たばこの不始末だったと発表されました。",
        "option_a": "機会",
        "option_b": "状況",
        "option_c": "原因",
        "option_d": "準備",
        "correct_answer": "C",
        "explanation": "「原因」は物事が起こるもとになる理由のことです。火事が起きた理由を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "努力した（　　）として、試験に合格することができました。",
        "option_a": "結果",
        "option_b": "原因",
        "option_c": "影響",
        "option_d": "連絡",
        "correct_answer": "A",
        "explanation": "「結果」は何かをした後に生じた状態や成果を意味します。努力によって生まれた成果を表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "海外留学は自分を成長させる良い（　　）です。",
        "option_a": "判断",
        "option_b": "機会",
        "option_c": "確認",
        "option_d": "説明",
        "correct_answer": "B",
        "explanation": "「機会」はある物事をするのに適したチャンスや時を意味します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "状況を分析して、正しい（　　）を下すことが管理職の役割です。",
        "option_a": "連絡",
        "option_b": "状況",
        "option_c": "判断",
        "option_d": "準備",
        "correct_answer": "C",
        "explanation": "「判断」は物事を考えて結論を出すことです。管理職が状況を分析して決定を下すことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "彼女の（　　）な行動に、みんなが感心しました。",
        "option_a": "適切",
        "option_b": "暖かい",
        "option_c": "速い",
        "option_d": "重い",
        "correct_answer": "A",
        "explanation": "「適切」はその状況や目的にぴったり合っているさまを表す言葉です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "彼は約束を（　　）する人なので、信頼されています。",
        "option_a": "実行",
        "option_b": "記録",
        "option_c": "増加",
        "option_d": "省略",
        "correct_answer": "A",
        "explanation": "「実行」は計画や約束などを実際に行うことです。約束を守ることを表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "この地域の人口は（　　）し続けています。",
        "option_a": "解消",
        "option_b": "減少",
        "option_c": "出発",
        "option_d": "発展",
        "correct_answer": "B",
        "explanation": "「減少」は数や量が少なくなることです。人口が少なくなり続けている状況を表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "新しいシステムを（　　）するために、社員全員が研修を受けました。",
        "option_a": "導入",
        "option_b": "表現",
        "option_c": "予測",
        "option_d": "観察",
        "correct_answer": "A",
        "explanation": "「導入」は新しいものを取り入れることです。新システムを会社に取り入れるための研修を表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "この仕事は（　　）が多く、なかなか終わりません。",
        "option_a": "手順",
        "option_b": "可能",
        "option_c": "注意",
        "option_d": "方法",
        "correct_answer": "A",
        "explanation": "「手順」は物事を進める順序や段階のことです。仕事の段階が多くて終わらない状況を表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "環境問題に（　　）して、社会全体で取り組む必要があります。",
        "option_a": "対応",
        "option_b": "流行",
        "option_c": "移動",
        "option_d": "保存",
        "correct_answer": "A",
        "explanation": "「対応」は物事や状況に合わせて適切に行動することです。環境問題に適切に取り組むことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "この商品は品質が高いのに（　　）が安いので、人気です。",
        "option_a": "価格",
        "option_b": "効果",
        "option_c": "様子",
        "option_d": "性質",
        "correct_answer": "A",
        "explanation": "「価格」は商品やサービスの値段のことです。品質と値段の対比を表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "彼の話は（　　）がなく、理解しにくいです。",
        "option_a": "論理",
        "option_b": "日程",
        "option_c": "感想",
        "option_d": "記念",
        "correct_answer": "A",
        "explanation": "「論理」は物事を筋道立てて考える理屈や道理のことです。話に筋道がなくて理解しにくいことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "プロジェクトの（　　）が遅れているので、急いで対処しなければなりません。",
        "option_a": "進行",
        "option_b": "習慣",
        "option_c": "年齢",
        "option_d": "方向",
        "correct_answer": "A",
        "explanation": "「進行」は物事が前に進んでいく状態やその具合です。プロジェクトが進む速度が遅れていることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "子供の（　　）な発想に大人たちは驚きました。",
        "option_a": "自由",
        "option_b": "豊か",
        "option_c": "細かい",
        "option_d": "複雑",
        "correct_answer": "B",
        "explanation": "「豊か」は十分にあってゆとりがある様子を表します。子供の発想が自由で豊かであることを意味します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "試験の日程を（　　）してから、勉強計画を立てました。",
        "option_a": "把握",
        "option_b": "感謝",
        "option_c": "利用",
        "option_d": "比較",
        "correct_answer": "A",
        "explanation": "「把握」は物事の状況や内容をしっかりと理解することです。日程をしっかり理解してから計画を立てた文脈に合います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "この計画には（　　）が多いので、もう一度見直す必要があります。",
        "option_a": "問題点",
        "option_b": "可能性",
        "option_c": "成果",
        "option_d": "協力",
        "correct_answer": "A",
        "explanation": "「問題点」は解決すべき課題や不具合となる部分のことです。計画に課題が多いことを表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "彼女はとても（　　）な人で、いつも周りの人を助けています。",
        "option_a": "親切",
        "option_b": "厳格",
        "option_c": "遠慮",
        "option_d": "静か",
        "correct_answer": "A",
        "explanation": "「親切」は他人に対して思いやりを持って接するさまを表す言葉です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "長年の（　　）があれば、困難な仕事もできます。",
        "option_a": "経験",
        "option_b": "目的",
        "option_c": "感情",
        "option_d": "意見",
        "correct_answer": "A",
        "explanation": "「経験」は実際に見たり行ったりすることで得た知識や技能のことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "この地域は観光地として（　　）されています。",
        "option_a": "注目",
        "option_b": "解決",
        "option_c": "判断",
        "option_d": "記録",
        "correct_answer": "A",
        "explanation": "「注目」は関心を持って注意して見ることです。観光地として多くの人が関心を持っていることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "その決定は多くの市民に（　　）を与えました。",
        "option_a": "不満",
        "option_b": "流行",
        "option_c": "記念",
        "option_d": "余裕",
        "correct_answer": "A",
        "explanation": "「不満」は期待や希望が満たされないことへの不平の気持ちです。決定に対して市民が不平を感じたことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "この研究の（　　）を発表するために、学会に参加しました。",
        "option_a": "成果",
        "option_b": "費用",
        "option_c": "条件",
        "option_d": "基本",
        "correct_answer": "A",
        "explanation": "「成果」は努力や行動によって得られた良い結果のことです。研究によって得られた結果を発表した文脈に合います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "彼は感情を（　　）せずに、いつも冷静に話します。",
        "option_a": "表現",
        "option_b": "消費",
        "option_c": "集中",
        "option_d": "変化",
        "correct_answer": "A",
        "explanation": "「表現」は気持ちや考えを言葉・行動などで外に表すことです。感情を外に出さない様子を表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "vocabulary",
        "question_text": "今後の（　　）について、上司と話し合いました。",
        "option_a": "方針",
        "option_b": "習慣",
        "option_c": "記事",
        "option_d": "景色",
        "correct_answer": "A",
        "explanation": "「方針」はある目標に向かって進む方向や基本的な考え方です。今後の基本的な方向について話し合ったことを表します。",
        "source_url": "",
        "passage": "",
    },
]

N3_GRAMMAR = [
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "家を出た（　　）、雨が降り始めた。",
        "option_a": "とたんに",
        "option_b": "ために",
        "option_c": "ものの",
        "option_d": "次第",
        "correct_answer": "A",
        "explanation": "「〜たとたんに」はある動作をした直後に別のことが起きたことを表します。「出たとたんに雨が降り始めた」という意味になります。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この地域の気温は年々上がり（　　）あります。",
        "option_a": "つつ",
        "option_b": "だらけ",
        "option_c": "向け",
        "option_d": "次第",
        "correct_answer": "A",
        "explanation": "「〜つつある」は変化が徐々に進行していることを表します。気温が少しずつ上がり続けている状態を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この部屋は間違い（　　）の報告書で散らかっています。",
        "option_a": "向け",
        "option_b": "だらけ",
        "option_c": "次第",
        "option_d": "に比べて",
        "correct_answer": "B",
        "explanation": "「〜だらけ」はそのものがたくさんあって困る様子を表します。間違いがたくさんある報告書が散らかっている状況を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "このアプリは子供（　　）に設計されています。",
        "option_a": "だらけ",
        "option_b": "次第",
        "option_c": "向け",
        "option_d": "つつ",
        "correct_answer": "C",
        "explanation": "「〜向け」はある対象のためにという意味を表します。子供を対象として設計されたアプリであることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "準備ができ（　　）、すぐに出発します。",
        "option_a": "次第",
        "option_b": "とたんに",
        "option_c": "に比べて",
        "option_d": "によると",
        "correct_answer": "A",
        "explanation": "「〜次第」は動詞に付いて「〜したらすぐに」という意味を表します。準備ができたらすぐに出発するという意味になります。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "去年（　　）今年は売り上げが大幅に増えました。",
        "option_a": "に比べて",
        "option_b": "によると",
        "option_c": "とたんに",
        "option_d": "ことにしている",
        "correct_answer": "A",
        "explanation": "「〜に比べて」は二つのものを比べることを表します。去年との比較で今年の売り上げが増えたことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "天気予報（　　）、明日は台風が来るそうです。",
        "option_a": "によると",
        "option_b": "に比べて",
        "option_c": "向け",
        "option_d": "だらけ",
        "correct_answer": "A",
        "explanation": "「〜によると」は情報の出所や根拠を示す表現です。天気予報という情報源からの内容を伝えています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "私は毎朝ジョギングする（　　）います。",
        "option_a": "ことにして",
        "option_b": "ものの",
        "option_c": "つつ",
        "option_d": "次第",
        "correct_answer": "A",
        "explanation": "「〜ことにしている」は自分で決めてそれを習慣にしていることを表します。毎朝ジョギングを習慣にしていることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "彼は試験に合格した（　　）、全然うれしそうではありません。",
        "option_a": "ものの",
        "option_b": "次第",
        "option_c": "とたんに",
        "option_d": "に比べて",
        "correct_answer": "A",
        "explanation": "「〜ものの」は逆接を表し、「〜だが、しかし」という意味です。合格したがうれしそうでないという対比を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "電話が鳴った（　　）、彼女は部屋から飛び出した。",
        "option_a": "とたんに",
        "option_b": "ものの",
        "option_c": "向け",
        "option_d": "によると",
        "correct_answer": "A",
        "explanation": "「〜たとたんに」はある出来事の直後に別のことが起きることを表します。電話が鳴った瞬間に飛び出したことを意味します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この町の人口は減り（　　）あります。",
        "option_a": "つつ",
        "option_b": "だらけ",
        "option_c": "ものの",
        "option_d": "向け",
        "correct_answer": "A",
        "explanation": "「〜つつある」は変化が継続して進行中であることを表します。人口が徐々に減り続けていることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この問題は複雑で、解決策は状況（　　）です。",
        "option_a": "次第",
        "option_b": "に比べて",
        "option_c": "だらけ",
        "option_d": "によると",
        "correct_answer": "A",
        "explanation": "「〜次第」は名詞に付いて「〜によって決まる」という意味を表します。解決策が状況に依存することを表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "先生の話（　　）、来週の試験は難しいそうです。",
        "option_a": "によると",
        "option_b": "ものの",
        "option_c": "とたんに",
        "option_d": "つつ",
        "correct_answer": "A",
        "explanation": "「〜によると」は「〜から聞いた情報では」という情報源を示す表現です。先生からの情報を伝えています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "私は毎晩日記をつける（　　）います。",
        "option_a": "ことにして",
        "option_b": "次第",
        "option_c": "だらけ",
        "option_d": "向け",
        "correct_answer": "A",
        "explanation": "「〜ことにしている」は自分が決めた習慣や規則を表します。毎晩日記をつけることを自分の習慣にしていることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この本は初心者（　　）なので、専門家には物足りないかもしれません。",
        "option_a": "向け",
        "option_b": "だらけ",
        "option_c": "次第",
        "option_d": "ものの",
        "correct_answer": "A",
        "explanation": "「〜向け」はある対象を目的にしたという意味を表します。初心者を対象にした本であることを示しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "去年の成績（　　）、今年の成績はずっと良くなりました。",
        "option_a": "に比べて",
        "option_b": "とたんに",
        "option_c": "ことにして",
        "option_d": "によると",
        "correct_answer": "A",
        "explanation": "「〜に比べて」は比較の基準を表します。去年と比べて今年の成績が向上したことを示しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この映画は子供向け（　　）、大人も十分に楽しめます。",
        "option_a": "ものの",
        "option_b": "次第",
        "option_c": "だらけ",
        "option_d": "に比べて",
        "correct_answer": "A",
        "explanation": "「〜ものの」は逆接を表します。子供向けであるが、大人も楽しめるという対比を示しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この部屋は泥（　　）で、すぐに掃除しなければなりません。",
        "option_a": "だらけ",
        "option_b": "向け",
        "option_c": "次第",
        "option_d": "ものの",
        "correct_answer": "A",
        "explanation": "「〜だらけ」はその状態が広がっていて困る様子を表します。泥がたくさんついて困っている状況を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "連絡が来（　　）、こちらから動くことができません。",
        "option_a": "次第",
        "option_b": "とたんに",
        "option_c": "つつ",
        "option_d": "に比べて",
        "correct_answer": "A",
        "explanation": "「〜次第」はその状況になったらすぐ、という意味です。連絡が来るまで動けないという意味になります。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "このソフトウェアは企業（　　）に開発されたものです。",
        "option_a": "向け",
        "option_b": "だらけ",
        "option_c": "ものの",
        "option_d": "によると",
        "correct_answer": "A",
        "explanation": "「〜向け」は特定の対象を意図して作られたことを表します。企業を対象として開発されたソフトウェアであることを示します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "彼女は泣き（　　）も、最後まで仕事を続けました。",
        "option_a": "つつ",
        "option_b": "だらけ",
        "option_c": "次第",
        "option_d": "とたんに",
        "correct_answer": "A",
        "explanation": "「〜つつ」は二つの動作が同時に行われることを表します。泣きながら仕事を続けたことを意味します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "ニュース（　　）、その地域で大きな地震があったそうです。",
        "option_a": "によると",
        "option_b": "ものの",
        "option_c": "向け",
        "option_d": "だらけ",
        "correct_answer": "A",
        "explanation": "「〜によると」は情報源を示す表現です。ニュースという情報源から得た情報を伝えています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "私は週に一度、図書館に行く（　　）います。",
        "option_a": "ことにして",
        "option_b": "とたんに",
        "option_c": "に比べて",
        "option_d": "次第",
        "correct_answer": "A",
        "explanation": "「〜ことにしている」は自分が決めた習慣を表す表現です。週に一度図書館に行くことを習慣にしていることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "試験に受かった（　　）、就職先がまだ決まっていません。",
        "option_a": "ものの",
        "option_b": "次第",
        "option_c": "だらけ",
        "option_d": "とたんに",
        "correct_answer": "A",
        "explanation": "「〜ものの」は「〜だが」という逆接を表します。試験には受かったが就職が決まっていないという対比を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "部長の話（　　）、来月から新しいプロジェクトが始まるそうです。",
        "option_a": "によると",
        "option_b": "に比べて",
        "option_c": "向け",
        "option_d": "つつ",
        "correct_answer": "A",
        "explanation": "「〜によると」は情報の出所を示します。部長から聞いた情報として新プロジェクトの開始を伝えています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "以前（　　）、最近は仕事量がずいぶん増えました。",
        "option_a": "に比べて",
        "option_b": "ものの",
        "option_c": "だらけ",
        "option_d": "とたんに",
        "correct_answer": "A",
        "explanation": "「〜に比べて」は比較を表します。以前と比べて最近の仕事量が増えたことを示しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "彼はためら（　　）も、最終的には引き受けることにしました。",
        "option_a": "いつつ",
        "option_b": "ものの",
        "option_c": "だらけ",
        "option_d": "次第",
        "correct_answer": "A",
        "explanation": "「〜つつ」は同時の動作や状態を表します。ためらいながらも引き受けることにしたという意味を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "決断できたら（　　）に連絡してください。",
        "option_a": "次第",
        "option_b": "だらけ",
        "option_c": "とたんに",
        "option_d": "ものの",
        "correct_answer": "A",
        "explanation": "「〜次第」はある状態になったらすぐに、という意味です。決断できたらすぐ連絡するよう求めています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この公園は子供たちの笑い声（　　）で、とてもにぎやかです。",
        "option_a": "だらけ",
        "option_b": "次第",
        "option_c": "ものの",
        "option_d": "向け",
        "correct_answer": "A",
        "explanation": "「〜だらけ」はそのものがあふれている状態を表します。子供の笑い声があふれてにぎやかな様子を表しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N3",
        "question_type": "grammar",
        "question_text": "この商品は高齢者（　　）に設計されているため、操作が簡単です。",
        "option_a": "向け",
        "option_b": "だらけ",
        "option_c": "ものの",
        "option_d": "によると",
        "correct_answer": "A",
        "explanation": "「〜向け」は特定の対象に合わせて作られたことを表します。高齢者を対象として設計されたため操作が簡単な商品です。",
        "source_url": "",
        "passage": "",
    },
]

N3_READING = [
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章によると、現代人が運動不足になる最も大きな原因は何ですか。",
        "option_a": "食事の内容が変化したから",
        "option_b": "デジタル機器の普及によって座って過ごす時間が増えたから",
        "option_c": "スポーツジムの数が減ったから",
        "option_d": "仕事の時間が短くなったから",
        "correct_answer": "B",
        "explanation": "文章では、スマートフォンやパソコンの普及によって人々が座ったまま過ごす時間が増え、それが運動不足の主な原因だと述べています。",
        "source_url": "",
        "passage": "現代社会では、スマートフォンやパソコンが急速に普及し、多くの人が一日中デジタル機器を使いながら座って過ごすようになりました。その結果、体を動かす機会が大幅に減り、運動不足が深刻な問題となっています。専門家によると、成人の約半数が一日に必要な運動量を満たしていないとのことです。運動不足は肥満や生活習慣病の原因となるだけでなく、精神的な健康にも悪影響を与えることが研究で明らかになっています。このような状況を改善するために、日常生活の中で意識的に体を動かす習慣を作ることが大切です。通勤時に一駅分歩く、エレベーターの代わりに階段を使うなど、小さな工夫から始めてみましょう。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章で筆者が最も言いたいことは何ですか。",
        "option_a": "読書は時間の無駄だ",
        "option_b": "電子書籍よりも紙の本の方が優れている",
        "option_c": "読書習慣を持つことで人生が豊かになる",
        "option_d": "図書館をもっと活用すべきだ",
        "correct_answer": "C",
        "explanation": "筆者は読書がもたらす様々な効果について述べ、読書習慣を持つことで語彙力や想像力が育まれ人生が豊かになると主張しています。",
        "source_url": "",
        "passage": "読書は人間の知識や感性を育てる最も効果的な方法の一つです。本を読むことで、私たちは語彙力や表現力が向上し、さまざまな分野の知識を得ることができます。また、小説などのフィクションを読むことで想像力が豊かになり、他者の立場から物事を考える力も身につきます。近年は電子書籍やインターネットの普及で読書の方法も変化していますが、どんな形であれ読書習慣を持つことの重要性は変わりません。忙しい毎日の中でも、寝る前の15分や通勤時間など、わずかな時間を活用して本を読む習慣を作ることで、人生はより豊かで充実したものになるでしょう。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "ゴミの分別について、この文章では何が重要だと述べていますか。",
        "option_a": "ゴミを減らすために買い物をしないこと",
        "option_b": "正しい分別方法を学び、地域のルールに従うこと",
        "option_c": "リサイクルより燃やすことの方が環境に良いこと",
        "option_d": "ゴミ収集の頻度を増やすこと",
        "correct_answer": "B",
        "explanation": "文章ではゴミの正しい分別が環境保護と資源の有効活用につながるとし、各自治体のルールを正しく理解して実行することが重要だと説明しています。",
        "source_url": "",
        "passage": "日本ではゴミの分別が非常に厳しく管理されており、地域によってルールが異なります。燃えるゴミ、燃えないゴミ、プラスチック、缶・ビン・ペットボトルなど、正しく分類することが求められています。ゴミを正しく分別することで、リサイクルできる資源が有効に活用され、環境への負担を減らすことができます。しかし、日本に来たばかりの外国人や、ルールを知らない人がゴミを誤って出すケースも少なくありません。自治体が配布する分別ガイドをよく読んで、地域のルールに従ってゴミを出すことが、地域社会の一員としての責任と言えるでしょう。一人ひとりの小さな努力が、住みやすい環境を守ることにつながります。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章で述べられている、テレワーク普及の問題点は何ですか。",
        "option_a": "交通費の負担が増加すること",
        "option_b": "社員間のコミュニケーションが不足しやすいこと",
        "option_c": "オフィスの維持費が高くなること",
        "option_d": "仕事の効率が大幅に下がること",
        "correct_answer": "B",
        "explanation": "文章では、テレワークには多くの利点がある一方で、社員同士が直接会う機会が減り、コミュニケーションが取りにくくなるという問題点が指摘されています。",
        "source_url": "",
        "passage": "新型コロナウイルスの流行をきっかけに、テレワークを導入する企業が急増しました。自宅で仕事ができるテレワークは、通勤時間の削減や柔軟な働き方を実現するなど、多くのメリットがあります。実際に、テレワーク導入後に生産性が上がったと回答した社員も多くいます。しかし一方で、社員同士が直接顔を合わせる機会が減ることで、チームのコミュニケーションが取りにくくなるという問題も生じています。特に新入社員にとっては、先輩から直接学ぶ機会が減ることが懸念されています。テレワークの利点を活かしながら、定期的なオフライン会議や懇親会を取り入れるなど、コミュニケーション不足を補う工夫が企業に求められています。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章によると、食品ロスを減らすためにできることとして述べられていないのはどれですか。",
        "option_a": "必要な分だけ買い物をする",
        "option_b": "食材を計画的に使う",
        "option_c": "外食を増やす",
        "option_d": "残り物を上手に活用する",
        "correct_answer": "C",
        "explanation": "文章では食品ロスを減らす方法として、計画的な買い物、食材の計画的な使用、残り物の活用について述べていますが、外食を増やすことは述べられていません。",
        "source_url": "",
        "passage": "食品ロスとは、まだ食べられるにもかかわらず捨てられてしまう食品のことです。日本では年間約600万トンもの食品ロスが発生しており、これは世界の食糧援助量のほぼ1.5倍に当たります。この問題を解決するために、私たちができることはいくつかあります。まず、買い物をするときは必要な分だけを購入し、衝動買いを避けることが大切です。次に、買ってきた食材を計画的に使い、冷蔵庫に長く入れたままにしないようにしましょう。また、夕食の残り物を翌日の昼食に活用するなど、食材を無駄なく使い切る工夫も重要です。食品ロスを減らすことは、家計の節約にもなり、環境保護にもつながります。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章が伝えたいメッセージは何ですか。",
        "option_a": "ボランティア活動は義務である",
        "option_b": "地域のつながりを大切にし、助け合うことが社会を豊かにする",
        "option_c": "個人の利益を最優先に考えるべきだ",
        "option_d": "ボランティア活動は時間の無駄だ",
        "correct_answer": "B",
        "explanation": "文章ではボランティア活動を通じた地域のつながりの大切さを強調し、人々が助け合うことで社会全体が豊かになると述べています。",
        "source_url": "",
        "passage": "近年、地域のつながりが薄れていると言われています。都市化や核家族化が進む中で、隣に誰が住んでいるか知らないという人も増えています。しかし、地域社会のつながりを大切にすることは、私たちの生活を豊かで安全なものにする上で非常に重要です。地域のボランティア活動や自治会の行事に積極的に参加することで、近隣の人たちとのつながりが生まれます。このようなつながりがあれば、困ったときに助け合うことができ、特に高齢者や子育て中の家庭にとって大きな支えになります。一人ひとりが地域社会に関心を持ち、お互いを思いやる気持ちを大切にすることで、住みやすい地域が作られていくのです。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章によると、睡眠不足が引き起こす問題として述べられていないものはどれですか。",
        "option_a": "集中力の低下",
        "option_b": "免疫力の低下",
        "option_c": "視力の低下",
        "option_d": "感情のコントロールが難しくなる",
        "correct_answer": "C",
        "explanation": "文章では睡眠不足の問題として集中力の低下、免疫力の低下、感情コントロールの困難を挙げていますが、視力の低下については述べられていません。",
        "source_url": "",
        "passage": "現代人の多くが睡眠不足に悩んでいます。仕事や学業のストレス、スマートフォンの使い過ぎなどが原因で、十分な睡眠を取れない人が増えています。睡眠不足は単に眠いというだけでなく、様々な健康問題を引き起こします。まず、脳が十分に休めないため、集中力や判断力が著しく低下します。また、免疫機能が弱まり、風邪などの感染症にかかりやすくなります。さらに、感情のコントロールが難しくなり、些細なことでイライラしたり、落ち込みやすくなるなど、精神的な健康にも悪影響を与えます。専門家は毎日7〜8時間の睡眠を推奨しています。質の良い睡眠のために、就寝前のスマートフォンの使用を控え、決まった時間に寝起きする習慣をつけることが大切です。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "筆者は日本語学習について、どのような考えを持っていますか。",
        "option_a": "日本語は難しすぎて、外国人には習得できない",
        "option_b": "文法の勉強よりも会話練習の方が大切だ",
        "option_c": "継続的な練習と実際に使う機会を増やすことが上達の鍵だ",
        "option_d": "日本語学習には特別な才能が必要だ",
        "correct_answer": "C",
        "explanation": "筆者は日本語学習において、毎日の継続的な練習と実際に日本語を使う機会を増やすことが大切だという考えを示しています。",
        "source_url": "",
        "passage": "日本語は世界の言語の中でも学ぶのが難しい言語の一つと言われています。ひらがな、カタカナ、漢字という三種類の文字を使い分けなければならず、敬語など複雑な表現もあります。しかし、多くの外国人学習者が日本語をマスターしているという事実があります。彼らに共通しているのは、毎日少しでも学習を続けるという習慣と、実際に日本語を使う機会を積極的に求めているという点です。テレビを日本語で見たり、日本人の友人と日本語で話したりすることで、教科書だけでは学べない自然な表現が身につきます。語学学習に特別な才能は必要ありません。大切なのは、継続する意志と、失敗を恐れずに使ってみる勇気です。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章によると、節水のためにできる方法として述べられているものはどれですか。",
        "option_a": "毎日シャワーの代わりにお風呂に入る",
        "option_b": "歯みがき中に水を流しっぱなしにしない",
        "option_c": "洗濯の回数を週に一度にする",
        "option_d": "食器洗いの際は熱いお湯を使う",
        "correct_answer": "B",
        "explanation": "文章では節水の方法として、歯みがき中や洗い物の際に水を出しっぱなしにしないことが具体的な方法として挙げられています。",
        "source_url": "",
        "passage": "水は地球上のすべての生き物にとって欠かせない資源ですが、世界では水不足に悩む地域も多くあります。日本では比較的水が豊富に思えますが、水を無駄にしないことは環境保護の観点からも非常に重要です。日常生活の中でできる節水の方法はいくつかあります。まず、歯みがきや洗い物をする際に、使わないときは水を止めるだけで、大幅な節水になります。また、シャワーの時間を短くしたり、お風呂の残り湯を洗濯に使ったりすることも効果的です。食器洗い機がある家庭では、手洗いより節水になる場合もあります。小さな積み重ねが大きな節水につながります。一人ひとりが水の大切さを意識し、日々の生活で節水に取り組むことが重要です。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章で述べられている、SNSの利点は何ですか。",
        "option_a": "個人情報が完全に守られること",
        "option_b": "すべての情報が正確であること",
        "option_c": "遠く離れた人とも簡単につながれること",
        "option_d": "収入を得ることができること",
        "correct_answer": "C",
        "explanation": "文章ではSNSの利点として、距離や時間に関係なく世界中の人とつながり、情報を共有できる点が挙げられています。",
        "source_url": "",
        "passage": "SNS（ソーシャルネットワーキングサービス）は現代社会において欠かせないコミュニケーションツールになっています。友人や家族との連絡はもちろん、遠く離れた国の人たちとも瞬時に情報を共有できるのは、SNSの大きな利点です。また、同じ趣味や関心を持つ人々のコミュニティに参加することで、新たな人間関係を築くこともできます。一方で、SNSには問題点もあります。偽の情報や誤った内容が拡散されやすく、それを真実と思って信じてしまう人も少なくありません。また、プライバシーの問題や、SNSに依存することで現実の生活に支障をきたすケースも増えています。SNSを便利に安全に使うためには、情報の真偽を確認する習慣と、適切な使用時間の管理が重要です。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章によると、子供の頃に外で遊ぶことの重要性は何ですか。",
        "option_a": "勉強の時間が減ること",
        "option_b": "体力だけでなく社会性や創造力も育まれること",
        "option_c": "テレビゲームへの興味が減ること",
        "option_d": "友達を作らなくてもよいこと",
        "correct_answer": "B",
        "explanation": "文章では、外遊びは体力の発達だけでなく、友達との関わりを通して社会性や問題解決力、創造力が育まれると述べています。",
        "source_url": "",
        "passage": "最近の子供たちは室内での遊びを好む傾向がありますが、外で遊ぶことの重要性は見直されるべきでしょう。外遊びは子供の体力や運動能力を高めるだけでなく、社会的な能力の発達にも大きく貢献します。友達と一緒に遊ぶことで、ルールを守ることや順番を待つこと、けんかを解決することなど、社会生活に必要なスキルを自然に学ぶことができます。また、自然の中での遊びは子供の想像力や創造力を豊かにします。石や木の枝など身近にあるものを使って遊ぶことで、創意工夫する力が育まれます。スマートフォンやゲームも楽しみの一つですが、外での遊びがもたらす経験は、それでは得られないものがたくさんあります。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章によると、日本の少子化問題に対して最も効果的な解決策として述べられているものはどれですか。",
        "option_a": "移民を積極的に受け入れること",
        "option_b": "子育て支援の充実と働き方改革を組み合わせること",
        "option_c": "出産に対する罰則を設けること",
        "option_d": "教育費を完全に無料にすること",
        "correct_answer": "B",
        "explanation": "文章では少子化対策として、子育て支援の充実と、特に女性が仕事と子育てを両立できる働き方改革の推進が最も重要だと述べています。",
        "source_url": "",
        "passage": "日本の少子化問題は年々深刻さを増しています。出生率の低下は労働力不足や社会保障制度の維持など、様々な問題を引き起こします。この問題を解決するために、政府や企業はさまざまな取り組みを行っています。保育所の増設や児童手当の拡充など、子育てしやすい環境を整えることは重要な一歩です。しかし、それだけでは十分ではありません。多くの若者が子供を持ちたくない理由として、仕事と家庭の両立の難しさや経済的な不安を挙げています。特に女性が出産後も仕事を続けられる環境を整えることや、男性も育児に積極的に参加できるよう働き方改革を進めることが、少子化対策として非常に重要です。社会全体で子育てを支える意識を高めることが、この問題の根本的な解決につながるでしょう。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章で筆者が主張していることは何ですか。",
        "option_a": "すべての仕事はAIに置き換えられる",
        "option_b": "AIを活用しながら人間ならではの能力を高めることが大切だ",
        "option_c": "AIの発展を規制すべきだ",
        "option_d": "AIは人間より常に優秀だ",
        "correct_answer": "B",
        "explanation": "筆者はAIの発展を否定せず、むしろその特性を理解した上で、AIが苦手とする創造性や感情的なつながりなど人間らしい能力を高めることが重要だと主張しています。",
        "source_url": "",
        "passage": "人工知能（AI）技術の急速な発展により、私たちの社会は大きく変わりつつあります。データの分析や単純作業など、これまで人間が行っていた多くの仕事がAIに代替されるようになっています。これを脅威と捉える人も多くいますが、私は必ずしもそうは考えません。AIが得意とする単純・反復的な作業をAIに任せることで、人間はより創造的で価値の高い仕事に集中できるようになります。大切なのは、AIの特性を正しく理解し、それを上手に活用することです。また、AIが苦手とすることにも注目すべきです。人との深い対話や感情的なつながりを必要とする仕事、倫理的な判断を求められる場面などでは、人間の能力が依然として不可欠です。AIと共存していく時代において、私たちは人間ならではの強みをさらに磨くことに力を注ぐべきでしょう。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章によると、旅行が人に与える効果として述べられていないものはどれですか。",
        "option_a": "異文化への理解が深まる",
        "option_b": "日常のストレスが解消される",
        "option_c": "語学力が必ず向上する",
        "option_d": "新しい視点で物事を見られるようになる",
        "correct_answer": "C",
        "explanation": "文章では旅行の効果として異文化理解、ストレス解消、新しい視点の獲得が挙げられていますが、語学力が必ず向上するとは述べられていません。",
        "source_url": "",
        "passage": "旅行は単なる娯楽ではなく、人間の成長に大きく貢献する体験です。見知らぬ土地を訪れ、異なる文化や習慣に触れることで、自分とは異なる価値観や考え方があることを実感できます。この体験は異文化への理解を深め、より広い視野で物事を考える力を育みます。また、日常の生活から離れることで、仕事や人間関係のストレスが自然に解消されます。旅先で新しい体験をする中で、自分が当たり前と思っていたことを見直すきっかけになることも多いです。旅行で出会った景色や人々との交流は、長く心に残り、その後の人生に影響を与えることがあります。国内旅行でも海外旅行でも、旅の本質は新しい何かとの出会いであり、その出会いがあなたの視野を広げてくれるでしょう。",
    },
    {
        "level": "N3",
        "question_type": "reading",
        "question_text": "この文章によると、スマートフォンが子供の発達に与える悪影響として述べられているものはどれですか。",
        "option_a": "視力の低下だけが問題である",
        "option_b": "対面でのコミュニケーション能力が育ちにくくなる恐れがある",
        "option_c": "学力が向上しすぎる",
        "option_d": "友達の数が増えすぎる",
        "correct_answer": "B",
        "explanation": "文章ではスマートフォンの過度な使用が、子供の対面でのコミュニケーション能力や集中力の発達を妨げる可能性があると述べています。",
        "source_url": "",
        "passage": "子供のスマートフォン使用が社会問題として取り上げられるようになってきました。幼い頃からスマートフォンに慣れ親しむことで、情報を素早く処理する能力が身につく一方、懸念される点もあります。画面を見つめる時間が長くなることで目への負担が増すことはよく知られていますが、それ以上に心配なのは、人との直接的なコミュニケーション能力への影響です。スマートフォンを通じた会話に慣れてしまうと、対面で話す能力やアイコンタクト、表情を読む力が十分に育ちにくくなる恐れがあります。また、短い動画やゲームに慣れることで、長時間一つのことに集中する力が育ちにくくなるとも言われています。子供のスマートフォン使用には、保護者が使用時間や内容にルールを設けて管理することが重要です。",
    },
]

N3_LISTENING = [
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の中で、田中さんが来週の月曜日にできないことは何ですか。",
        "option_a": "会議に出席すること",
        "option_b": "資料を準備すること",
        "option_c": "取引先を訪問すること",
        "option_d": "報告書を提出すること",
        "correct_answer": "C",
        "explanation": "田中さんは来週月曜日に会議があるため、その日の取引先への訪問はできないと話しています。",
        "source_url": "",
        "passage": "山田：田中さん、来週の月曜日に取引先のABC商事を訪問してもらえますか。新しいプロジェクトについて説明する必要があるんです。田中：来週月曜日ですか。すみません、その日は午後から部長との重要な会議があるんです。資料の準備も月曜の午前中にしなければならないので、訪問はちょっと難しいです。山田：そうですか。では、火曜日はどうですか。田中：火曜日なら大丈夫です。報告書の提出は月曜日の夕方までに終わらせますので、火曜日は問題ありません。山田：わかりました。ではABC商事に火曜日で連絡しておきますね。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話で、女性が注文を変えた理由は何ですか。",
        "option_a": "値段が高かったから",
        "option_b": "アレルギーがあったから",
        "option_c": "日替わりランチが売り切れだったから",
        "option_d": "友達が同じものを頼んだから",
        "correct_answer": "C",
        "explanation": "女性は最初に日替わりランチを注文しようとしましたが、店員から本日分が売り切れと伝えられたため、注文を変更しました。",
        "source_url": "",
        "passage": "店員：いらっしゃいませ。ご注文はお決まりですか。女性：はい、日替わりランチをひとつお願いします。店員：大変申し訳ございません。本日の日替わりランチはただいま売り切れとなっております。女性：あら、そうなんですか。じゃあ、えーと…パスタセットはありますか。店員：はい、ただいまご用意できます。ドリンクはコーヒーと紅茶からお選びいただけます。女性：では、パスタセットとコーヒーをお願いします。店員：かしこまりました。少々お待ちください。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の中で、二人は何について話し合っていますか。",
        "option_a": "新入社員の研修プログラム",
        "option_b": "会社の年末パーティーの計画",
        "option_c": "プロジェクトの締め切りの変更",
        "option_d": "オフィスの引っ越し",
        "correct_answer": "B",
        "explanation": "二人は会社の年末パーティーについて、場所や日程、招待する人数などを話し合っています。",
        "source_url": "",
        "passage": "木村：鈴木さん、今年の年末パーティーのことなんですが、もうお店の予約はしましたか。鈴木：まだなんです。去年と同じお店にしようかと思っているんですが、何人ぐらい参加する予定ですか。木村：今のところ、30人ぐらいです。でも、まだ返事をもらっていない人が5人ぐらいいて。鈴木：じゃあ、35人で予約しておいた方が安心ですね。日程は12月20日でいいですか。木村：はい、その日にしましょう。では、お店の予約をお願いしてもいいですか。鈴木：わかりました。今日の昼休みに連絡してみます。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話で、学生は先生に何を相談していますか。",
        "option_a": "卒業論文のテーマの変更",
        "option_b": "アルバイトの紹介",
        "option_c": "留学のための奨学金",
        "option_d": "授業の欠席理由",
        "correct_answer": "A",
        "explanation": "学生は当初決めていた卒業論文のテーマでは十分なデータが集まらないため、テーマを変更したいと先生に相談しています。",
        "source_url": "",
        "passage": "学生：先生、少しよろしいですか。卒業論文のことでご相談があるのですが。先生：ああ、どうぞ。何かあったの？学生：実は、当初決めていたテーマで調査を進めていたんですが、データがなかなか集まらなくて…テーマを変えてもいいでしょうか。先生：テーマを変えたいんですね。今どんな状況か、もう少し詳しく話してください。学生：インタビュー協力者を30人集める予定だったんですが、今のところ10人しか見つかっていないんです。先生：なるほど。確かに10人では分析が難しいね。では、似たテーマでデータが集めやすいものを一緒に考えてみましょう。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の内容から、男性はこの後どうすることになりましたか。",
        "option_a": "すぐに銀行に行く",
        "option_b": "ATMで手続きをする",
        "option_c": "後日、必要書類を持って銀行に来る",
        "option_d": "電話で申し込みをする",
        "correct_answer": "C",
        "explanation": "銀行の窓口で、担当者が口座開設には本人確認書類が必要と説明し、男性は必要書類を持参して後日来ることになりました。",
        "source_url": "",
        "passage": "男性：すみません、口座を作りたいんですが。銀行員：ありがとうございます。口座開設のご希望ですね。本日はお持ちのものをお持ちでしょうか。男性：えっと、財布は持っています。銀行員：口座を開設するためには、運転免許証やパスポートなどの本人確認書類が必要なんですよ。今日はお持ちですか。男性：あ、今日は持ってきていないです。銀行員：でしたら、本人確認書類と印鑑をお持ちになって、またご来店いただけますか。マイナンバーカードでも大丈夫ですよ。男性：わかりました。では明日また来ます。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話で、二人が話している主な内容は何ですか。",
        "option_a": "新しいスポーツジムの開業",
        "option_b": "運動不足を解消するための取り組み",
        "option_c": "マラソン大会への参加",
        "option_d": "ダイエット食品の効果",
        "correct_answer": "B",
        "explanation": "二人は最近運動が足りないと感じており、どうすれば日常的に体を動かせるかについて話し合っています。",
        "source_url": "",
        "passage": "佐藤：最近、全然運動できていなくて体が重いんですよね。加藤さんは何か運動していますか。加藤：私も同じです。テレワークになってから、本当に体を動かさなくなって。それで最近、毎日の通勤代わりに30分ウォーキングを始めたんです。佐藤：それいいですね。私はなかなか時間が取れなくて。加藤：ウォーキングなら特別な準備がいらないし、朝少し早く起きるだけで始められますよ。佐藤：確かに。それなら私もできそうです。一緒に朝ウォーキングしませんか。加藤：いいですね！では、来週の月曜日から始めましょうか。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の中で、イベントの変更点は何ですか。",
        "option_a": "開催場所が変わった",
        "option_b": "参加費が上がった",
        "option_c": "開催日が1週間延期になった",
        "option_d": "イベントが中止になった",
        "correct_answer": "C",
        "explanation": "担当者が、予定していたイベントは会場の都合により開催日を一週間後に延期することになったと話しています。",
        "source_url": "",
        "passage": "女性：もしもし、先日申し込みをした文化祭イベントについてなんですが。担当者：はい、ご確認の件でしょうか。実は、先ほど全員の方にメールでご連絡したのですが、イベントの日程が変更になりました。女性：えっ、変更ですか。どうなったんですか。担当者：会場の設備工事の関係で、予定していた10月15日から、1週間後の10月22日に延期させていただくことになりました。場所は同じ市民ホールで、時間も同じく午後2時からです。女性：わかりました。10月22日ですね。参加費は変わりませんか。担当者：はい、参加費の変更はございません。ご不便をおかけして申し訳ございません。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の中で、上司が部下に頼んだことは何ですか。",
        "option_a": "クライアントへのメールを送ること",
        "option_b": "会議室を予約すること",
        "option_c": "プレゼンの資料を印刷すること",
        "option_d": "議事録を作成すること",
        "correct_answer": "B",
        "explanation": "上司は明日の午後3時から行われるクライアントとの打ち合わせのために、会議室を予約しておくよう部下に頼みました。",
        "source_url": "",
        "passage": "上司：中村さん、明日の午後3時からクライアントとの打ち合わせがあるんだけど。中村：はい、スケジュールは確認しています。上司：悪いんだけど、会議室の予約をしておいてもらえる？8人ぐらい入れる部屋が必要なんだ。中村：わかりました。第一会議室か第二会議室ですね。プロジェクターは必要ですか。上司：うん、プレゼンをするから必要だね。あと、打ち合わせが終わったら議事録も作ってほしいんだけど、それは打ち合わせが終わってからでいいよ。中村：承知しました。では、今すぐ会議室の予約をしておきます。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話で、女の子が学校を休んだ理由は何ですか。",
        "option_a": "旅行に行っていたから",
        "option_b": "発熱で体調が悪かったから",
        "option_c": "試合のために練習があったから",
        "option_d": "家族の行事があったから",
        "correct_answer": "B",
        "explanation": "女の子は昨日から熱があり、医者に行ったところ安静にするよう言われたため学校を休んだと話しています。",
        "source_url": "",
        "passage": "友達A：早紀ちゃん、昨日学校どうしたの？心配したよ。友達B（早紀）：ごめん、連絡しなくて。昨日の朝から急に熱が出ちゃって。友達A：えっ、大丈夫？今日は来られてよかったけど。友達B：うん、昨日お医者さんに行ったら、熱が38度あって。薬をもらって、ゆっくり休んでいたら今朝は熱が下がったんだ。友達A：そっか、辛かったね。授業ノートが必要だったら貸すよ。友達B：ありがとう！特に数学が心配で。友達A：じゃあ、放課後コピーしてあげるね。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話で、二人はどこに食事に行くことにしましたか。",
        "option_a": "イタリア料理のレストラン",
        "option_b": "焼き肉のお店",
        "option_c": "中華料理のお店",
        "option_d": "和食のレストラン",
        "correct_answer": "D",
        "explanation": "最初に焼き肉やイタリア料理などが提案されましたが、最終的に二人は和食のレストランに行くことに決めました。",
        "source_url": "",
        "passage": "男性：今夜の夕食、どこに行こうか。焼き肉はどうかな。女性：焼き肉もいいけど、昨日も肉料理だったし…イタリアンはどう？男性：イタリアンか。でも、最近パスタを食べたばかりだなあ。女性：そうだね。じゃあ、お魚が食べたいな。和食ってどう？男性：和食いいね！駅前に新しい和食のお店ができたんだけど、まだ行ったことないから行ってみない？女性：ぜひ行ってみましょう。お刺身が食べたかったんだ。男性：じゃあ、7時に駅前で待ち合わせにしよう。女性：わかった、楽しみにしてる。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の中で、引っ越しの手伝いをできない理由は何ですか。",
        "option_a": "体調が悪いから",
        "option_b": "仕事が入っているから",
        "option_c": "その日は出張があるから",
        "option_d": "家族の用事があるから",
        "correct_answer": "D",
        "explanation": "友人は引っ越しの手伝いをしたいが、その日は子供の発表会があり家族で行かなければならないため、手伝いができないと話しています。",
        "source_url": "",
        "passage": "Aさん：来週の土曜日に引っ越しするんだけど、手伝ってもらえないかな。Bさん：来週の土曜日か。本当に手伝いたいんだけど、その日は子供の発表会があるんだよ。Aさん：そうなんだ。Bさん：家族みんなで行く予定になっていて、ずっと前から決まっていたんだ。ごめんね、本当に。Aさん：そっか、全然大丈夫だよ。子供の発表会は大切だもの。Bさん：引っ越し先が落ち着いたら、絶対遊びに行くよ。Aさん：ありがとう。他の人にも声をかけてみるね。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話で、商品について男性が確認したことは何ですか。",
        "option_a": "商品の色の種類",
        "option_b": "返品の条件",
        "option_c": "保証期間の長さ",
        "option_d": "配送の日数",
        "correct_answer": "C",
        "explanation": "男性は購入を検討している電化製品について、故障した場合の対応として保証期間がどのくらいかを店員に確認しています。",
        "source_url": "",
        "passage": "店員：こちらの電子レンジは、最新モデルで操作も簡単ですよ。男性：そうですか。気になっているんですが、もし故障した場合はどうなりますか。店員：はい、購入日から1年間のメーカー保証がついています。男性：1年ですか。それは短いですね。延長保証はありますか。店員：はい、当店では3年間の延長保証プランもご用意しています。追加料金は商品価格の10%になります。男性：なるほど。色は何色がありますか。店員：白と黒の2色です。男性：延長保証も含めて検討してみます。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の中で、二人の先生はどんなことを心配していますか。",
        "option_a": "生徒の成績が下がっていること",
        "option_b": "来月の修学旅行の準備が遅れていること",
        "option_c": "生徒の授業中の居眠りが増えていること",
        "option_d": "学校の設備が古くなっていること",
        "correct_answer": "C",
        "explanation": "二人の先生は、最近授業中に居眠りをする生徒が増えており、その原因として夜遅くまでスマートフォンを使っていることを懸念しています。",
        "source_url": "",
        "passage": "先生A：最近、授業中に寝ている生徒が多くなった気がしませんか。先生B：私のクラスも同じです。特に午後の授業が酷くて。先生A：原因はなんでしょうね。先生B：保護者の方から聞いたんですが、夜遅くまでスマートフォンを使っている子が多いみたいで。深夜1時や2時まで起きているという話も聞きました。先生A：それは問題ですね。睡眠不足では集中して勉強できませんよね。先生B：保護者と連携して、家庭でのスマートフォンの使い方のルールを話し合う機会を作った方がいいかもしれません。先生A：そうですね、来月の保護者会でその議題を取り上げましょう。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の中で、図書館について述べられていることは何ですか。",
        "option_a": "来週から改装のため閉館する",
        "option_b": "開館時間が延長された",
        "option_c": "新しい本のコーナーが増えた",
        "option_d": "インターネットが使えるようになった",
        "correct_answer": "B",
        "explanation": "図書館の司書が、利用者からの要望を受けて、今月から平日の閉館時間が1時間延長されたことを知らせています。",
        "source_url": "",
        "passage": "利用者：すみません、今日は何時まで開いていますか。司書：本日は午後8時までです。今月から平日の閉館時間が1時間延長になりました。利用者：えっ、そうなんですか。以前は7時でしたよね。司書：はい、利用者の方から「もう少し遅くまで開いていてほしい」というご意見を多くいただいたので、今月から変更しました。利用者：それは助かります。仕事帰りに来やすくなりますね。司書：はい、ぜひご活用ください。土日祝日は従来通り午後5時までとなっておりますのでご注意ください。利用者：わかりました、ありがとうございます。",
    },
    {
        "level": "N3",
        "question_type": "listening",
        "is_active": False,
        "question_text": "会話の内容から、この後二人はどうすることにしましたか。",
        "option_a": "すぐに会議を始める",
        "option_b": "資料を確認してから会議の日程を決める",
        "option_c": "メールで各部署に連絡する",
        "option_d": "部長に相談してから決める",
        "correct_answer": "D",
        "explanation": "二人は新しいプロジェクトについての会議日程を決めようとしていますが、重要な決定なので自分たちだけでは決められず、まず部長に相談することにしました。",
        "source_url": "",
        "passage": "田村：新しいプロジェクトのキックオフ会議の日程を決めたいんですが、来週の木曜日はどうでしょうか。松本：木曜日は各部署のマネージャーが会議に参加できるか確認しないといけないですね。関係部署が多いので。田村：そうですね。でもこの件は部長も関係しているから、勝手に日程を決めてしまってもいいのかな。松本：それは心配ですね。まず部長に相談してから、日程を決めた方が良いと思います。田村：そうしましょう。では、午後に部長にお時間をいただいて相談しに行きましょう。松本：はい、私も一緒に行きます。",
    },
]


def get_n3_questions() -> list[dict]:
    return N3_VOCAB + N3_GRAMMAR + N3_READING + N3_LISTENING
