N2_VOCAB = [
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「促進」の意味として正しいものはどれですか。",
        "option_a": "物事が進むように働きかけること",
        "option_b": "物事を止めること",
        "option_c": "物事を記録すること",
        "option_d": "物事を比較すること",
        "correct_answer": "A",
        "explanation": "「促進」は物事が進むよう促すことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「維持」の意味として正しいものはどれですか。",
        "option_a": "新しく作ること",
        "option_b": "現状をそのまま保つこと",
        "option_c": "大きく変えること",
        "option_d": "完全になくすこと",
        "correct_answer": "B",
        "explanation": "「維持」は現状を保ち続けることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「構成」の意味として正しいものはどれですか。",
        "option_a": "いくつかの要素を組み合わせてまとまりを作ること",
        "option_b": "ものを壊すこと",
        "option_c": "情報を収集すること",
        "option_d": "問題を解決すること",
        "correct_answer": "A",
        "explanation": "「構成」は複数の要素を組み合わせて一つの全体を作ることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「傾向」の意味として正しいものはどれですか。",
        "option_a": "物事が一定の方向に向かう性質",
        "option_b": "まったく変化しない状態",
        "option_c": "突然起こる出来事",
        "option_d": "正確な数値や量",
        "correct_answer": "A",
        "explanation": "「傾向」は物事がある方向に偏りやすい性質を指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「背景」の意味として正しいものはどれですか。",
        "option_a": "物事の前面に見えるもの",
        "option_b": "物事の後ろにある状況や事情",
        "option_c": "物事の将来の計画",
        "option_d": "物事の正確な定義",
        "correct_answer": "B",
        "explanation": "「背景」はある出来事や状況の裏にある事情や環境を指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「概要」の意味として正しいものはどれですか。",
        "option_a": "詳細な説明",
        "option_b": "内容の大まかなあらまし",
        "option_c": "正確な数値データ",
        "option_d": "最終的な結論",
        "correct_answer": "B",
        "explanation": "「概要」は物事の大体の内容をまとめたものを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「具体的」の反対の意味を持つ言葉はどれですか。",
        "option_a": "現実的",
        "option_b": "抽象的",
        "option_c": "客観的",
        "option_d": "積極的",
        "correct_answer": "B",
        "explanation": "「具体的」の反対語は「抽象的」で、はっきりした形のない概念的なものを指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「抽象的」の意味として正しいものはどれですか。",
        "option_a": "誰でも分かるほど分かりやすいこと",
        "option_b": "実体がなく概念的であること",
        "option_c": "非常に詳しいこと",
        "option_d": "感情的であること",
        "correct_answer": "B",
        "explanation": "「抽象的」は具体的な形や実体がなく、概念として捉えられることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「客観的」の意味として正しいものはどれですか。",
        "option_a": "個人の感情や意見に基づいていること",
        "option_b": "個人の感情を交えず事実に基づいていること",
        "option_c": "多くの人が知っていること",
        "option_d": "目標に向かって積極的に行動すること",
        "correct_answer": "B",
        "explanation": "「客観的」は自分の感情や主観を除いて物事を見ることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「慣用句」の意味として正しいものはどれですか。",
        "option_a": "新しく作られた言葉",
        "option_b": "慣習的に使われる決まった意味の言い回し",
        "option_c": "外国語から取り入れた言葉",
        "option_d": "専門的な技術用語",
        "correct_answer": "B",
        "explanation": "「慣用句」は習慣的に使われ、特定の意味を持つ言葉の組み合わせを指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「影響」の意味として正しいものはどれですか。",
        "option_a": "他に作用を及ぼすこと",
        "option_b": "他と比較すること",
        "option_c": "他を模倣すること",
        "option_d": "他を排除すること",
        "correct_answer": "A",
        "explanation": "「影響」はある物事が別の物事に何らかの作用を与えることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「貢献」の意味として正しいものはどれですか。",
        "option_a": "社会や他者の役に立つために力を尽くすこと",
        "option_b": "自分だけの利益を追求すること",
        "option_c": "他者の行動を批判すること",
        "option_d": "責任を他者に押しつけること",
        "correct_answer": "A",
        "explanation": "「貢献」は社会や他の人のために役立つことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「把握」の意味として正しいものはどれですか。",
        "option_a": "物事をしっかり理解して掌握すること",
        "option_b": "物事を無視すること",
        "option_c": "物事を記録すること",
        "option_d": "物事を変更すること",
        "correct_answer": "A",
        "explanation": "「把握」は状況や内容をしっかりと理解・掌握することを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「妥当」の意味として正しいものはどれですか。",
        "option_a": "程度や内容が適切でふさわしいこと",
        "option_b": "非常に優れていること",
        "option_c": "普通よりも劣っていること",
        "option_d": "珍しくて貴重なこと",
        "correct_answer": "A",
        "explanation": "「妥当」は判断や処置が適切で道理にかなっていることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「矛盾」の意味として正しいものはどれですか。",
        "option_a": "二つの事柄が食い違って両立しないこと",
        "option_b": "二つの事柄がぴったり合うこと",
        "option_c": "一つの問題が解決されること",
        "option_d": "複数の意見が一致すること",
        "correct_answer": "A",
        "explanation": "「矛盾」は前後の事柄が食い違い、論理的に両立しないことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「効率」の意味として正しいものはどれですか。",
        "option_a": "使った労力に対して得られる成果の割合",
        "option_b": "仕事の難易度",
        "option_c": "作業にかかる合計時間",
        "option_d": "チームの人数",
        "correct_answer": "A",
        "explanation": "「効率」は投入した労力や資源に対する成果の比率を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「批判」の意味として正しいものはどれですか。",
        "option_a": "物事の良い点だけを評価すること",
        "option_b": "物事の誤りや問題点を指摘して論じること",
        "option_c": "物事を深く研究すること",
        "option_d": "物事を分かりやすく説明すること",
        "correct_answer": "B",
        "explanation": "「批判」は物事の欠点や問題点を取り上げて論じることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「前提」の意味として正しいものはどれですか。",
        "option_a": "議論や行動の出発点となる条件や仮定",
        "option_b": "議論の最終的な結論",
        "option_c": "過去に起きた出来事",
        "option_d": "将来の目標",
        "correct_answer": "A",
        "explanation": "「前提」は推論や議論の基礎となる条件や仮定を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「柔軟」の意味として正しいものはどれですか。",
        "option_a": "状況に応じてうまく対応できること",
        "option_b": "一つのやり方に固執すること",
        "option_c": "非常に強い力を持つこと",
        "option_d": "感情的に振る舞うこと",
        "correct_answer": "A",
        "explanation": "「柔軟」は状況の変化に応じて適切に対応できる性質を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「根拠」の意味として正しいものはどれですか。",
        "option_a": "判断や意見の基礎となる事実や理由",
        "option_b": "最終的な結論",
        "option_c": "将来の計画",
        "option_d": "過去の失敗",
        "correct_answer": "A",
        "explanation": "「根拠」は主張や判断を支える事実・理由・証拠を意味する。",
        "source_url": "",
        "passage": "",
    },
]

N2_GRAMMAR = [
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼の行動は会社の方針（　）ものだった。",
        "option_a": "に反した",
        "option_b": "に基づいた",
        "option_c": "を踏まえた",
        "option_d": "に際した",
        "correct_answer": "A",
        "explanation": "「〜に反して」は期待や規則に逆らっていることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "市場の調査結果（　）、新しい商品を開発することにした。",
        "option_a": "に反して",
        "option_b": "を踏まえて",
        "option_c": "にもかかわらず",
        "option_d": "どころか",
        "correct_answer": "B",
        "explanation": "「〜を踏まえて」はある事実や状況を考慮した上で行動することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "この研究は最新のデータ（　）進められている。",
        "option_a": "に際して",
        "option_b": "ばかりか",
        "option_c": "に基づいて",
        "option_d": "どころか",
        "correct_answer": "C",
        "explanation": "「〜に基づいて」はある基準や根拠に従って行動することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "大雨（　）、試合は予定通り行われた。",
        "option_a": "を踏まえて",
        "option_b": "に基づいて",
        "option_c": "にもかかわらず",
        "option_d": "に反して",
        "correct_answer": "C",
        "explanation": "「〜にもかかわらず」は逆接を表し、予想に反して別の結果になることを示す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼女は英語（　）フランス語も話せる。",
        "option_a": "どころか",
        "option_b": "ばかりか",
        "option_c": "に反して",
        "option_d": "に際して",
        "correct_answer": "B",
        "explanation": "「〜ばかりか」は一つのことに加えてさらに別のことも成立することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼はお礼を言う（　）、文句まで言い出した。",
        "option_a": "ばかりか",
        "option_b": "にもかかわらず",
        "option_c": "どころか",
        "option_d": "を踏まえて",
        "correct_answer": "C",
        "explanation": "「〜どころか」はある事柄が全く当てはまらず、むしろ逆の状況であることを強調する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "出発（　）、もう一度荷物を確認してください。",
        "option_a": "に基づいて",
        "option_b": "に際して",
        "option_c": "を踏まえて",
        "option_d": "ばかりか",
        "correct_answer": "B",
        "explanation": "「〜に際して」は重要な場面や時点において行動することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼の意見は常識（　）発言だと感じた。",
        "option_a": "を踏まえた",
        "option_b": "に基づいた",
        "option_c": "に反した",
        "option_d": "に際した",
        "correct_answer": "C",
        "explanation": "「〜に反した」は一般的な期待や常識に反することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "今回の経験（　）、次のプロジェクトを計画したい。",
        "option_a": "を踏まえて",
        "option_b": "にもかかわらず",
        "option_c": "どころか",
        "option_d": "ばかりか",
        "correct_answer": "A",
        "explanation": "「〜を踏まえて」は過去の経験や情報を参考にして次の行動を決めることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "この法律は憲法（　）制定されている。",
        "option_a": "どころか",
        "option_b": "に反して",
        "option_c": "に基づいて",
        "option_d": "ばかりか",
        "correct_answer": "C",
        "explanation": "「〜に基づいて」はある基準や原則に従って物事が行われることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "疲れている（　）、彼女は残業を引き受けた。",
        "option_a": "どころか",
        "option_b": "ばかりか",
        "option_c": "に際して",
        "option_d": "にもかかわらず",
        "correct_answer": "D",
        "explanation": "「〜にもかかわらず」は不利な状況にありながらも別の行動をとることを示す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "この製品は安い（　）品質も優れている。",
        "option_a": "にもかかわらず",
        "option_b": "に反して",
        "option_c": "ばかりか",
        "option_d": "に基づいて",
        "correct_answer": "C",
        "explanation": "「〜ばかりか」は一つの優れた点に加えてさらに別の良い点もあることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "入学（　）必要な書類を揃えてください。",
        "option_a": "に反して",
        "option_b": "に際して",
        "option_c": "どころか",
        "option_d": "を踏まえて",
        "correct_answer": "B",
        "explanation": "「〜に際して」はある重要な機会や時点に合わせて準備することを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "彼は謝る（　）、さらに問題を起こした。",
        "option_a": "ばかりか",
        "option_b": "に基づいて",
        "option_c": "どころか",
        "option_d": "を踏まえて",
        "correct_answer": "C",
        "explanation": "「〜どころか」は予想とは全く逆の、より否定的な状況を強調する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "アンケートの結果（　）サービスを改善します。",
        "option_a": "にもかかわらず",
        "option_b": "に反して",
        "option_c": "に際して",
        "option_d": "に基づいて",
        "correct_answer": "D",
        "explanation": "「〜に基づいて」は収集したデータや事実を根拠として行動することを表す。",
        "source_url": "",
        "passage": "",
    },
]

N2_READING = [
    # Passage 1
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "この文章の主なテーマは何ですか。",
        "option_a": "環境問題と経済成長の両立",
        "option_b": "再生可能エネルギーの技術的な課題",
        "option_c": "化石燃料の将来性",
        "option_d": "国際的なエネルギー価格の変動",
        "correct_answer": "A",
        "explanation": "文章全体が環境保護と経済発展を同時に実現する可能性について論じている。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "再生可能エネルギーの普及によって何が可能になりましたか。",
        "option_a": "化石燃料の完全な廃止",
        "option_b": "温室効果ガスを抑えながら経済を発展させること",
        "option_c": "初期投資コストの完全な解消",
        "option_d": "政府の役割の縮小",
        "correct_answer": "B",
        "explanation": "文章は再生可能エネルギーが排出を抑えつつ経済発展を可能にすると述べている。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "文章によると、どのような課題が残っていますか。",
        "option_a": "初期投資の大きさと技術的な課題",
        "option_b": "環境問題への無関心",
        "option_c": "経済成長の停滞",
        "option_d": "再生可能エネルギーの需要不足",
        "correct_answer": "A",
        "explanation": "文章は「初期投資の大きさや技術的な課題も残っており」と明示している。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "持続可能な社会を実現するために必要なことは何ですか。",
        "option_a": "政府だけが取り組むこと",
        "option_b": "企業の利益を最優先すること",
        "option_c": "個人・企業・政府が一体となって行動すること",
        "option_d": "技術開発を中止すること",
        "correct_answer": "C",
        "explanation": "文章の最後に「個人・企業・政府が一体となって行動する必要がある」と述べられている。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "「継続的な取り組み」が求められているのは誰ですか。",
        "option_a": "研究者と学生",
        "option_b": "政府や企業",
        "option_c": "外国の機関",
        "option_d": "地域のボランティア",
        "correct_answer": "B",
        "explanation": "文章は「政府や企業の継続的な取り組みが求められている」と述べている。",
        "source_url": "",
        "passage": "近年、環境問題への関心が高まる中、経済成長と環境保護の両立が重要な課題となっている。再生可能エネルギーの普及により、温室効果ガスの排出を抑えながら経済を発展させることが可能になってきた。しかし、初期投資の大きさや技術的な課題も残っており、政府や企業の継続的な取り組みが求められている。持続可能な社会を実現するためには、個人・企業・政府が一体となって行動する必要がある。",
    },
    # Passage 2
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "この文章が最も伝えたいことは何ですか。",
        "option_a": "読書は時間の無駄である",
        "option_b": "読書習慣が思考力や語彙力の向上に役立つ",
        "option_c": "電子書籍は紙の本より優れている",
        "option_d": "学校教育では読書を教えるべきではない",
        "correct_answer": "B",
        "explanation": "文章は読書が思考力・語彙力・共感力を高める効果について説明している。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "フィクションを読むことでどのような力が養われますか。",
        "option_a": "計算能力",
        "option_b": "体力",
        "option_c": "他者の視点を理解し共感する力",
        "option_d": "記憶力",
        "correct_answer": "C",
        "explanation": "文章は「フィクションを読むことで他者の視点を理解し、共感する力も養われる」と述べている。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "現代人にとって読書のどのような点が難しいですか。",
        "option_a": "本の値段が高いこと",
        "option_b": "読書の時間を確保すること",
        "option_c": "本を見つけること",
        "option_d": "読書の内容を理解すること",
        "correct_answer": "B",
        "explanation": "文章は「忙しい現代人にとって読書の時間を確保するのは難しい」と述べている。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "多様な文章に触れることでどのような力が身につきますか。",
        "option_a": "外国語を話す力",
        "option_b": "論理的に考える力",
        "option_c": "素早く行動する力",
        "option_d": "数字を扱う力",
        "correct_answer": "B",
        "explanation": "文章は「多様な文章に触れることで、論理的に考える力が自然と身につく」と述べている。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "文章が勧める読書の方法はどれですか。",
        "option_a": "週末にまとめて長時間読む",
        "option_b": "毎日少しずつ読む習慣をつける",
        "option_c": "専門書だけを読む",
        "option_d": "音読で本を読む",
        "correct_answer": "B",
        "explanation": "文章は「毎日少しずつ読む習慣をつけることが大切だ」と勧めている。",
        "source_url": "",
        "passage": "読書は単なる娯楽にとどまらず、思考力や語彙力を高める効果があると言われている。多様な文章に触れることで、論理的に考える力が自然と身につく。また、小説などのフィクションを読むことで他者の視点を理解し、共感する力も養われる。忙しい現代人にとって読書の時間を確保するのは難しいが、毎日少しずつ読む習慣をつけることが大切だ。",
    },
]

N2_LISTENING = [
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "二人は何について話していますか。",
        "option_a": "週末の旅行計画",
        "option_b": "会議の準備と資料の確認",
        "option_c": "新しい社員の採用",
        "option_d": "来月の予算について",
        "correct_answer": "B",
        "explanation": "会話は明日の会議に向けた資料確認と準備について話している。",
        "source_url": "",
        "passage": "男性：明日の会議の資料、もう確認しましたか。\n女性：はい、一通り見ました。でも、3ページ目のグラフが少し分かりにくいかもしれません。\n男性：そうですか。修正しておきます。他に気になる点はありますか。\n女性：いいえ、それ以外は大丈夫だと思います。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "女性は何が問題だと言っていますか。",
        "option_a": "資料全体が分かりにくい",
        "option_b": "3ページ目のグラフが分かりにくい",
        "option_c": "会議の日程が間違っている",
        "option_d": "資料のページ数が足りない",
        "correct_answer": "B",
        "explanation": "女性は「3ページ目のグラフが少し分かりにくいかもしれません」と述べている。",
        "source_url": "",
        "passage": "男性：明日の会議の資料、もう確認しましたか。\n女性：はい、一通り見ました。でも、3ページ目のグラフが少し分かりにくいかもしれません。\n男性：そうですか。修正しておきます。他に気になる点はありますか。\n女性：いいえ、それ以外は大丈夫だと思います。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "男性はこの後何をしますか。",
        "option_a": "新しい資料を作る",
        "option_b": "会議を延期する",
        "option_c": "グラフを修正する",
        "option_d": "女性に連絡する",
        "correct_answer": "C",
        "explanation": "男性は「修正しておきます」と言ったのでグラフを直すことが分かる。",
        "source_url": "",
        "passage": "男性：明日の会議の資料、もう確認しましたか。\n女性：はい、一通り見ました。でも、3ページ目のグラフが少し分かりにくいかもしれません。\n男性：そうですか。修正しておきます。他に気になる点はありますか。\n女性：いいえ、それ以外は大丈夫だと思います。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "女性が店員に最初に聞いたことは何ですか。",
        "option_a": "商品の値段",
        "option_b": "この商品が別の色で売っているかどうか",
        "option_c": "商品の返品方法",
        "option_d": "商品の使い方",
        "correct_answer": "B",
        "explanation": "女性は最初に「別の色はありますか」と色の種類について尋ねている。",
        "source_url": "",
        "passage": "女性：すみません、このバッグ、別の色はありますか。\n店員：はい、黒と紺がございます。こちらの青以外でよろしければご案内できます。\n女性：では、黒を見せてもらえますか。\n店員：少々お待ちください。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この店ではどの色のバッグが買えますか。",
        "option_a": "青・黒・紺",
        "option_b": "赤・青・黒",
        "option_c": "黒・白・紺",
        "option_d": "青・赤・白",
        "correct_answer": "A",
        "explanation": "会話から、青・黒・紺の三色が存在することが分かる。",
        "source_url": "",
        "passage": "女性：すみません、このバッグ、別の色はありますか。\n店員：はい、黒と紺がございます。こちらの青以外でよろしければご案内できます。\n女性：では、黒を見せてもらえますか。\n店員：少々お待ちください。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "女性は最終的にどうしましたか。",
        "option_a": "青いバッグを買った",
        "option_b": "黒いバッグを見せてもらうことにした",
        "option_c": "何も買わずに帰った",
        "option_d": "紺のバッグを注文した",
        "correct_answer": "B",
        "explanation": "女性は「黒を見せてもらえますか」と言い、黒を確認することにした。",
        "source_url": "",
        "passage": "女性：すみません、このバッグ、別の色はありますか。\n店員：はい、黒と紺がございます。こちらの青以外でよろしければご案内できます。\n女性：では、黒を見せてもらえますか。\n店員：少々お待ちください。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "二人は何について話していますか。",
        "option_a": "レポートの締め切りと提出方法",
        "option_b": "授業の時間割の変更",
        "option_c": "試験の結果",
        "option_d": "図書館の利用方法",
        "correct_answer": "A",
        "explanation": "会話はレポートの締め切りと提出方法について確認している。",
        "source_url": "",
        "passage": "学生A：来週のレポート、メールで提出していいですか。\n学生B：先生が印刷して出すように言っていたよ。\n学生A：そうか、知らなかった。締め切りはいつまでだっけ。\n学生B：金曜日の授業が終わるまでだって。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "レポートの締め切りはいつですか。",
        "option_a": "来週の月曜日",
        "option_b": "金曜日の授業が終わるまで",
        "option_c": "今週の水曜日",
        "option_d": "メールで送った時点",
        "correct_answer": "B",
        "explanation": "学生Bが「金曜日の授業が終わるまでだって」と述べている。",
        "source_url": "",
        "passage": "学生A：来週のレポート、メールで提出していいですか。\n学生B：先生が印刷して出すように言っていたよ。\n学生A：そうか、知らなかった。締め切りはいつまでだっけ。\n学生B：金曜日の授業が終わるまでだって。",
    },
]


N2_EXTRA = [
    # --- 15 Vocabulary ---
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「概念」の意味として正しいものはどれですか。",
        "option_a": "具体的なものの形や大きさ",
        "option_b": "物事の本質をまとめた抽象的な考え方",
        "option_c": "過去に起きた歴史的な出来事",
        "option_d": "数値で表せる客観的なデータ",
        "correct_answer": "B",
        "explanation": "「概念」はある物事の本質的な内容を言葉や思考で捉えた抽象的な考えを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「論点」の意味として正しいものはどれですか。",
        "option_a": "議論や問題の中心となる争点",
        "option_b": "議論の結論や答え",
        "option_c": "発言者の個人的な感情",
        "option_d": "会議の開催場所",
        "correct_answer": "A",
        "explanation": "「論点」は議論や討論において争われる中心的な問題点を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「妥協」の意味として正しいものはどれですか。",
        "option_a": "自分の意見を完全に押し通すこと",
        "option_b": "お互いが譲り合って折り合いをつけること",
        "option_c": "相手の意見を全面的に受け入れること",
        "option_d": "議論を打ち切ること",
        "correct_answer": "B",
        "explanation": "「妥協」は双方が主張を一部譲り合って合意に至ることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「補足」の意味として正しいものはどれですか。",
        "option_a": "内容を削除すること",
        "option_b": "足りない部分を付け加えて補うこと",
        "option_c": "全体を最初からやり直すこと",
        "option_d": "相手の発言を否定すること",
        "correct_answer": "B",
        "explanation": "「補足」は説明や情報に不足している部分を追加して補うことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「見解」の意味として正しいものはどれですか。",
        "option_a": "ある事柄に対する個人や組織の考えや意見",
        "option_b": "公式に認められた規則",
        "option_c": "統計的なデータや数値",
        "option_d": "過去の判例や前例",
        "correct_answer": "A",
        "explanation": "「見解」は物事に対して持つ考えや意見、判断のことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「影響力」の意味として正しいものはどれですか。",
        "option_a": "他に変化や効果を与える力や作用",
        "option_b": "物理的な重さや質量",
        "option_c": "法律上の権限や資格",
        "option_d": "経済的な資産や財力",
        "correct_answer": "A",
        "explanation": "「影響力」は他の人や物事に変化をもたらすことができる力を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「実態」の意味として正しいものはどれですか。",
        "option_a": "表面上の印象や見かけ",
        "option_b": "物事の実際の状態やありのままの姿",
        "option_c": "将来の理想的な姿",
        "option_d": "過去の記録や統計",
        "correct_answer": "B",
        "explanation": "「実態」は外見や建前ではなく、物事の実際の状態を指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「文脈」の意味として正しいものはどれですか。",
        "option_a": "文章や話の前後のつながりや流れ",
        "option_b": "文章の文字数や長さ",
        "option_c": "話し手の声の大きさやトーン",
        "option_d": "文章に使われている漢字の種類",
        "correct_answer": "A",
        "explanation": "「文脈」は言葉や出来事の前後関係から生まれる意味のつながりを指す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「慣行」の意味として正しいものはどれですか。",
        "option_a": "新しく制定された法律や規則",
        "option_b": "以前から行われてきた習慣的なやり方",
        "option_c": "特定の人だけが使う専門的な技術",
        "option_d": "一時的に設けられた例外措置",
        "correct_answer": "B",
        "explanation": "「慣行」は社会や組織の中で長年にわたって行われてきた習慣的な行為を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「示唆」の意味として正しいものはどれですか。",
        "option_a": "直接的に命令すること",
        "option_b": "それとなく暗示したり、ヒントを与えたりすること",
        "option_c": "公式に発表・宣言すること",
        "option_d": "強制的に従わせること",
        "correct_answer": "B",
        "explanation": "「示唆」は直接言わずに間接的にある考えや方向性をほのめかすことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「懸案」の意味として正しいものはどれですか。",
        "option_a": "すでに解決済みの問題",
        "option_b": "以前から解決されずに残っている問題や課題",
        "option_c": "新たに発生した緊急の問題",
        "option_d": "専門家だけが扱う技術的な問題",
        "correct_answer": "B",
        "explanation": "「懸案」はずっと未解決のまま残っている問題や検討事項を意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「節約」の意味として正しいものはどれですか。",
        "option_a": "むだを省いてお金や資源を大切に使うこと",
        "option_b": "大量に購入して備蓄すること",
        "option_c": "高品質なものにお金をかけること",
        "option_d": "利益を上げるために投資すること",
        "correct_answer": "A",
        "explanation": "「節約」は無駄を減らしてお金や資源を効率よく使うことを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「展望」の意味として正しいものはどれですか。",
        "option_a": "過去を振り返り反省すること",
        "option_b": "将来の見通しや広い視野で物事を見ること",
        "option_c": "現在の状況を細かく分析すること",
        "option_d": "他者の行動を監視すること",
        "correct_answer": "B",
        "explanation": "「展望」は将来に対する見通しや広い視点から物事を眺めることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「整備」の意味として正しいものはどれですか。",
        "option_a": "設備や制度などを整えて使いやすくすること",
        "option_b": "古いものを廃棄すること",
        "option_c": "費用を削減すること",
        "option_d": "計画を中止すること",
        "correct_answer": "A",
        "explanation": "「整備」は機器・制度・環境などを手入れして十分に機能する状態に整えることを意味する。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "vocabulary",
        "question_text": "「互いに」の意味として正しいものはどれですか。",
        "option_a": "片方だけが行動すること",
        "option_b": "双方がそれぞれ相手に対して同様に",
        "option_c": "第三者が仲介に入ること",
        "option_d": "順番に交代しながら",
        "correct_answer": "B",
        "explanation": "「互いに」は関係する双方がそれぞれ相手に対して同じように行うことを意味する。",
        "source_url": "",
        "passage": "",
    },
    # --- 10 Grammar ---
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "留学（　）、日本語の勉強をより真剣に始めた。",
        "option_a": "をきっかけに",
        "option_b": "に先立って",
        "option_c": "を通じて",
        "option_d": "にしたがって",
        "correct_answer": "A",
        "explanation": "「〜をきっかけに」はある出来事が行動や変化のきっかけ・契機になったことを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "式典（　）、会場の準備を入念に行った。",
        "option_a": "をきっかけに",
        "option_b": "に先立って",
        "option_c": "ことから",
        "option_d": "にしたがって",
        "correct_answer": "B",
        "explanation": "「〜に先立って」はある重要な行事や出来事の前に準備などをすることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "インターネット（　）、世界中の人と情報を共有できるようになった。",
        "option_a": "をきっかけに",
        "option_b": "に先立って",
        "option_c": "を通じて",
        "option_d": "ことから",
        "correct_answer": "C",
        "explanation": "「〜を通じて」はある手段・媒介を経由して何かが行われることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "この地域は海に近い（　）、新鮮な魚介類が豊富だ。",
        "option_a": "にしたがって",
        "option_b": "を通じて",
        "option_c": "に先立って",
        "option_d": "ことから",
        "correct_answer": "D",
        "explanation": "「〜ことから」はある事実や状況を根拠として結論や判断を導くことを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "経験を積む（　）、仕事の質も向上した。",
        "option_a": "ことから",
        "option_b": "に先立って",
        "option_c": "にしたがって",
        "option_d": "をきっかけに",
        "correct_answer": "C",
        "explanation": "「〜にしたがって」はある変化に比例して別の変化が生じることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "その事故（　）、安全基準の見直しが行われた。",
        "option_a": "に先立って",
        "option_b": "をきっかけに",
        "option_c": "にしたがって",
        "option_d": "を通じて",
        "correct_answer": "B",
        "explanation": "「〜をきっかけに」はある出来事が変化や行動の出発点になったことを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "会議（　）、関係者全員に連絡してください。",
        "option_a": "を通じて",
        "option_b": "ことから",
        "option_c": "に先立って",
        "option_d": "をきっかけに",
        "correct_answer": "C",
        "explanation": "「〜に先立って」は何かが始まる前に事前準備として行うことを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "気温が下がる（　）、外出する人が減ってきた。",
        "option_a": "をきっかけに",
        "option_b": "を通じて",
        "option_c": "に先立って",
        "option_d": "にしたがって",
        "correct_answer": "D",
        "explanation": "「〜にしたがって」は一方の変化に伴って他方も変化していくことを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "この作品は作者の実体験（　）書かれたと言われている。",
        "option_a": "にしたがって",
        "option_b": "に先立って",
        "option_c": "ことから",
        "option_d": "をきっかけに",
        "correct_answer": "C",
        "explanation": "「〜ことから」は根拠・由来を示し、そこから何かが導かれることを表す。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N2",
        "question_type": "grammar",
        "question_text": "SNS（　）、多くの人が社会問題に関心を持つようになった。",
        "option_a": "に先立って",
        "option_b": "を通じて",
        "option_c": "ことから",
        "option_d": "にしたがって",
        "correct_answer": "B",
        "explanation": "「〜を通じて」はある媒体や手段を介して何かが広まることを表す。",
        "source_url": "",
        "passage": "",
    },
    # --- 15 Reading (3 passages × 5 questions) ---
    # Passage A: テレワーク
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "この文章が最も伝えたいことは何ですか。",
        "option_a": "テレワークは全ての企業に義務付けるべきだ",
        "option_b": "テレワークには利点と課題の両面があり適切な対応が必要だ",
        "option_c": "オフィス勤務は時代遅れで廃止すべきだ",
        "option_d": "テレワークの普及で通勤問題はすでに解決された",
        "correct_answer": "B",
        "explanation": "文章はテレワークのメリットと課題を両方述べ、適切な取り組みの必要性を主張している。",
        "source_url": "",
        "passage": "テレワークの普及により、働き方が大きく変化している。通勤時間の削減や育児との両立がしやすくなるなど、従業員にとって多くの利点がある。一方で、チームのコミュニケーションが取りにくくなる、仕事とプライベートの境界が曖昧になるといった課題も指摘されている。企業は生産性を維持しながら従業員の満足度を高めるために、テレワーク制度の整備と職場環境の改善を継続的に進めることが求められる。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "テレワークの利点として文章に挙げられているものはどれですか。",
        "option_a": "会議の回数が増えること",
        "option_b": "通勤時間の削減と育児との両立",
        "option_c": "給与が上がること",
        "option_d": "新しいスキルが身につくこと",
        "correct_answer": "B",
        "explanation": "文章は「通勤時間の削減や育児との両立がしやすくなる」を利点として挙げている。",
        "source_url": "",
        "passage": "テレワークの普及により、働き方が大きく変化している。通勤時間の削減や育児との両立がしやすくなるなど、従業員にとって多くの利点がある。一方で、チームのコミュニケーションが取りにくくなる、仕事とプライベートの境界が曖昧になるといった課題も指摘されている。企業は生産性を維持しながら従業員の満足度を高めるために、テレワーク制度の整備と職場環境の改善を継続的に進めることが求められる。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "テレワークの課題として挙げられていないものはどれですか。",
        "option_a": "チームのコミュニケーションが取りにくい",
        "option_b": "仕事とプライベートの境界が曖昧になる",
        "option_c": "インターネット環境の整備が難しい",
        "option_d": "上の選択肢はすべて挙げられているわけではない",
        "correct_answer": "C",
        "explanation": "文章はコミュニケーションの問題とプライベートとの境界の問題を挙げているが、インターネット環境については触れていない。",
        "source_url": "",
        "passage": "テレワークの普及により、働き方が大きく変化している。通勤時間の削減や育児との両立がしやすくなるなど、従業員にとって多くの利点がある。一方で、チームのコミュニケーションが取りにくくなる、仕事とプライベートの境界が曖昧になるといった課題も指摘されている。企業は生産性を維持しながら従業員の満足度を高めるために、テレワーク制度の整備と職場環境の改善を継続的に進めることが求められる。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "企業に求められていることは何ですか。",
        "option_a": "従業員全員をオフィス勤務に戻すこと",
        "option_b": "テレワーク制度の整備と職場環境の改善を継続すること",
        "option_c": "賃金を引き上げること",
        "option_d": "海外への事業展開を進めること",
        "correct_answer": "B",
        "explanation": "文章は「テレワーク制度の整備と職場環境の改善を継続的に進めることが求められる」と述べている。",
        "source_url": "",
        "passage": "テレワークの普及により、働き方が大きく変化している。通勤時間の削減や育児との両立がしやすくなるなど、従業員にとって多くの利点がある。一方で、チームのコミュニケーションが取りにくくなる、仕事とプライベートの境界が曖昧になるといった課題も指摘されている。企業は生産性を維持しながら従業員の満足度を高めるために、テレワーク制度の整備と職場環境の改善を継続的に進めることが求められる。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "「生産性を維持しながら」という表現から分かることは何ですか。",
        "option_a": "生産性を下げてでも従業員を優先する必要がある",
        "option_b": "生産性と従業員満足度の両立を目指している",
        "option_c": "生産性のためなら従業員の満足度は無視してよい",
        "option_d": "生産性はテレワークとは無関係である",
        "correct_answer": "B",
        "explanation": "「生産性を維持しながら従業員の満足度を高める」という表現は両方の実現を同時に目指していることを示す。",
        "source_url": "",
        "passage": "テレワークの普及により、働き方が大きく変化している。通勤時間の削減や育児との両立がしやすくなるなど、従業員にとって多くの利点がある。一方で、チームのコミュニケーションが取りにくくなる、仕事とプライベートの境界が曖昧になるといった課題も指摘されている。企業は生産性を維持しながら従業員の満足度を高めるために、テレワーク制度の整備と職場環境の改善を継続的に進めることが求められる。",
    },
    # Passage B: 地域の高齢化
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "この文章の主なテーマは何ですか。",
        "option_a": "都市と農村の経済格差",
        "option_b": "地域の高齢化がもたらす問題とその対応",
        "option_c": "少子化対策としての移民受け入れ",
        "option_d": "医療技術の進歩と平均寿命の延伸",
        "correct_answer": "B",
        "explanation": "文章全体が地域の高齢化問題とその解決に向けた取り組みについて述べている。",
        "source_url": "",
        "passage": "日本の多くの地方では高齢化が急速に進み、労働力不足や地域サービスの低下が深刻な問題となっている。若い世代が都市へ移住することで人口が減少し、地域経済の活力が失われつつある。こうした状況に対応するため、一部の自治体ではITを活用した行政サービスの効率化や、移住促進策による人口回復を試みている。地域の持続可能性を高めるためには、住民・行政・企業が連携して地域の魅力を発信し続けることが重要だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "地方の人口が減少している主な原因は何ですか。",
        "option_a": "出生率の低下だけが原因",
        "option_b": "若い世代が都市へ移住すること",
        "option_c": "外国人労働者が増えないこと",
        "option_d": "農業の機械化が進まないこと",
        "correct_answer": "B",
        "explanation": "文章は「若い世代が都市へ移住することで人口が減少し」と明示している。",
        "source_url": "",
        "passage": "日本の多くの地方では高齢化が急速に進み、労働力不足や地域サービスの低下が深刻な問題となっている。若い世代が都市へ移住することで人口が減少し、地域経済の活力が失われつつある。こうした状況に対応するため、一部の自治体ではITを活用した行政サービスの効率化や、移住促進策による人口回復を試みている。地域の持続可能性を高めるためには、住民・行政・企業が連携して地域の魅力を発信し続けることが重要だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "一部の自治体が試みていることとして正しいものはどれですか。",
        "option_a": "都市への移住を奨励すること",
        "option_b": "ITを活用した行政サービスの効率化と移住促進策",
        "option_c": "農業補助金の廃止",
        "option_d": "高齢者施設の建設を止めること",
        "correct_answer": "B",
        "explanation": "文章は「ITを活用した行政サービスの効率化や、移住促進策による人口回復を試みている」と述べている。",
        "source_url": "",
        "passage": "日本の多くの地方では高齢化が急速に進み、労働力不足や地域サービスの低下が深刻な問題となっている。若い世代が都市へ移住することで人口が減少し、地域経済の活力が失われつつある。こうした状況に対応するため、一部の自治体ではITを活用した行政サービスの効率化や、移住促進策による人口回復を試みている。地域の持続可能性を高めるためには、住民・行政・企業が連携して地域の魅力を発信し続けることが重要だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "地域の持続可能性を高めるために重要なことは何ですか。",
        "option_a": "政府だけが単独で政策を進めること",
        "option_b": "住民・行政・企業が連携して地域の魅力を発信すること",
        "option_c": "地方の全ての産業を廃止して農業に集中すること",
        "option_d": "都市への人口集中をさらに促進すること",
        "correct_answer": "B",
        "explanation": "文章は「住民・行政・企業が連携して地域の魅力を発信し続けることが重要だ」と述べている。",
        "source_url": "",
        "passage": "日本の多くの地方では高齢化が急速に進み、労働力不足や地域サービスの低下が深刻な問題となっている。若い世代が都市へ移住することで人口が減少し、地域経済の活力が失われつつある。こうした状況に対応するため、一部の自治体ではITを活用した行政サービスの効率化や、移住促進策による人口回復を試みている。地域の持続可能性を高めるためには、住民・行政・企業が連携して地域の魅力を発信し続けることが重要だ。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "「地域経済の活力が失われつつある」とはどういう意味ですか。",
        "option_a": "地域の経済が急激に成長している",
        "option_b": "地域の経済力が徐々に低下している状態が続いている",
        "option_c": "地域経済がすでに完全に崩壊した",
        "option_d": "地域経済は変化なく安定している",
        "correct_answer": "B",
        "explanation": "「〜つつある」は変化が進行中であることを表し、活力が徐々に低下し続けていることを意味する。",
        "source_url": "",
        "passage": "日本の多くの地方では高齢化が急速に進み、労働力不足や地域サービスの低下が深刻な問題となっている。若い世代が都市へ移住することで人口が減少し、地域経済の活力が失われつつある。こうした状況に対応するため、一部の自治体ではITを活用した行政サービスの効率化や、移住促進策による人口回復を試みている。地域の持続可能性を高めるためには、住民・行政・企業が連携して地域の魅力を発信し続けることが重要だ。",
    },
    # Passage C: 食文化とグローバル化
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "この文章が述べている食文化の変化とは何ですか。",
        "option_a": "伝統的な和食が完全に消えつつある",
        "option_b": "グローバル化によって各国の食文化が相互に影響し合っている",
        "option_c": "外国料理は日本では受け入れられていない",
        "option_d": "日本食は海外でまったく人気がない",
        "correct_answer": "B",
        "explanation": "文章はグローバル化によって食文化が国境を越えて影響し合う現状を説明している。",
        "source_url": "",
        "passage": "グローバル化の進展により、世界各地の食文化が互いに影響し合うようになっている。日本でも寿司やラーメンが世界的に人気を集める一方、様々な国の料理が日本の食卓に取り入れられている。こうした食文化の交流は、地域の特色ある食材や調理法への関心を高める機会にもなっている。ただし、伝統的な食文化を守ることと新しい食文化を受け入れることのバランスを保つことが課題となっている。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "日本食について文章で述べられていることはどれですか。",
        "option_a": "寿司とラーメンが世界的に人気を集めている",
        "option_b": "日本食は海外では理解されにくい",
        "option_c": "日本食は栄養価が低いと指摘されている",
        "option_d": "和食レストランは減少している",
        "correct_answer": "A",
        "explanation": "文章は「寿司やラーメンが世界的に人気を集める」と述べている。",
        "source_url": "",
        "passage": "グローバル化の進展により、世界各地の食文化が互いに影響し合うようになっている。日本でも寿司やラーメンが世界的に人気を集める一方、様々な国の料理が日本の食卓に取り入れられている。こうした食文化の交流は、地域の特色ある食材や調理法への関心を高める機会にもなっている。ただし、伝統的な食文化を守ることと新しい食文化を受け入れることのバランスを保つことが課題となっている。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "食文化の交流が生む機会として文章に述べられているものはどれですか。",
        "option_a": "食品輸出の増加",
        "option_b": "地域の特色ある食材や調理法への関心が高まること",
        "option_c": "外食産業の競争激化",
        "option_d": "農業人口の増加",
        "correct_answer": "B",
        "explanation": "文章は食文化の交流が「地域の特色ある食材や調理法への関心を高める機会になっている」と述べている。",
        "source_url": "",
        "passage": "グローバル化の進展により、世界各地の食文化が互いに影響し合うようになっている。日本でも寿司やラーメンが世界的に人気を集める一方、様々な国の料理が日本の食卓に取り入れられている。こうした食文化の交流は、地域の特色ある食材や調理法への関心を高める機会にもなっている。ただし、伝統的な食文化を守ることと新しい食文化を受け入れることのバランスを保つことが課題となっている。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "文章が指摘している課題は何ですか。",
        "option_a": "食品の安全基準を国際的に統一すること",
        "option_b": "伝統的な食文化の保護と新しい食文化受け入れのバランス",
        "option_c": "農産物の輸入規制を強化すること",
        "option_d": "料理人の育成に予算を増やすこと",
        "correct_answer": "B",
        "explanation": "文章は「伝統的な食文化を守ることと新しい食文化を受け入れることのバランスを保つことが課題」と述べている。",
        "source_url": "",
        "passage": "グローバル化の進展により、世界各地の食文化が互いに影響し合うようになっている。日本でも寿司やラーメンが世界的に人気を集める一方、様々な国の料理が日本の食卓に取り入れられている。こうした食文化の交流は、地域の特色ある食材や調理法への関心を高める機会にもなっている。ただし、伝統的な食文化を守ることと新しい食文化を受け入れることのバランスを保つことが課題となっている。",
    },
    {
        "level": "N2",
        "question_type": "reading",
        "question_text": "「互いに影響し合う」とはどういう意味ですか。",
        "option_a": "一方だけが他方に作用を与える",
        "option_b": "双方がそれぞれ相手に作用を与え合う",
        "option_c": "全く関係がなく独立している",
        "option_d": "一方が他方を完全に支配する",
        "correct_answer": "B",
        "explanation": "「互いに影響し合う」は双方が相手に対してそれぞれ影響を与えていることを意味する。",
        "source_url": "",
        "passage": "グローバル化の進展により、世界各地の食文化が互いに影響し合うようになっている。日本でも寿司やラーメンが世界的に人気を集める一方、様々な国の料理が日本の食卓に取り入れられている。こうした食文化の交流は、地域の特色ある食材や調理法への関心を高める機会にもなっている。ただし、伝統的な食文化を守ることと新しい食文化を受け入れることのバランスを保つことが課題となっている。",
    },
    # --- 10 Listening ---
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "二人は何について話していますか。",
        "option_a": "新しいアルバイトの探し方",
        "option_b": "プロジェクトの締め切りと作業分担",
        "option_c": "来週の旅行の行き先",
        "option_d": "会社の新しい規則",
        "correct_answer": "B",
        "explanation": "会話はプロジェクトの締め切りが迫る中での作業分担の調整について話し合っている。",
        "source_url": "",
        "passage": "男性：このプロジェクト、来週の金曜が締め切りだよね。進捗はどう？\n女性：デザイン部分はほぼ終わりました。でも、データ集計がまだ残っています。\n男性：じゃあ、僕がデータ集計を手伝うよ。\n女性：助かります。よろしくお願いします。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "女性はどの作業が終わっていないと言っていますか。",
        "option_a": "デザイン部分",
        "option_b": "プレゼンの準備",
        "option_c": "データ集計",
        "option_d": "報告書の作成",
        "correct_answer": "C",
        "explanation": "女性は「データ集計がまだ残っています」と述べている。",
        "source_url": "",
        "passage": "男性：このプロジェクト、来週の金曜が締め切りだよね。進捗はどう？\n女性：デザイン部分はほぼ終わりました。でも、データ集計がまだ残っています。\n男性：じゃあ、僕がデータ集計を手伝うよ。\n女性：助かります。よろしくお願いします。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "男性はこの後何をすることになりましたか。",
        "option_a": "デザインを修正する",
        "option_b": "データ集計を手伝う",
        "option_c": "締め切りを延長する",
        "option_d": "上司に報告する",
        "correct_answer": "B",
        "explanation": "男性が「僕がデータ集計を手伝うよ」と申し出て、女性が了承した。",
        "source_url": "",
        "passage": "男性：このプロジェクト、来週の金曜が締め切りだよね。進捗はどう？\n女性：デザイン部分はほぼ終わりました。でも、データ集計がまだ残っています。\n男性：じゃあ、僕がデータ集計を手伝うよ。\n女性：助かります。よろしくお願いします。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "二人は何について話していますか。",
        "option_a": "引っ越し先のマンションの条件",
        "option_b": "駅前の新しいカフェ",
        "option_c": "地域の清掃活動への参加",
        "option_d": "週末の買い物リスト",
        "correct_answer": "A",
        "explanation": "会話は引っ越しを検討している人が物件の条件について話し合っている。",
        "source_url": "",
        "passage": "女性：来月引っ越すんだけど、駅から近いほうがいいかな。\n男性：通勤を考えると、やっぱり駅近のほうが楽だよ。\n女性：でも、家賃が高くなるよね。\n男性：少し遠くてもバス路線があれば大丈夫じゃないかな。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "男性が駅近を勧める理由は何ですか。",
        "option_a": "駅近のほうが家賃が安いから",
        "option_b": "通勤が楽だから",
        "option_c": "スーパーが多いから",
        "option_d": "治安が良いから",
        "correct_answer": "B",
        "explanation": "男性は「通勤を考えると、やっぱり駅近のほうが楽だよ」と述べている。",
        "source_url": "",
        "passage": "女性：来月引っ越すんだけど、駅から近いほうがいいかな。\n男性：通勤を考えると、やっぱり駅近のほうが楽だよ。\n女性：でも、家賃が高くなるよね。\n男性：少し遠くてもバス路線があれば大丈夫じゃないかな。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "男性が駅近でない場合の条件として挙げているものは何ですか。",
        "option_a": "駐車場があること",
        "option_b": "バス路線があること",
        "option_c": "自転車が使えること",
        "option_d": "職場まで徒歩で行けること",
        "correct_answer": "B",
        "explanation": "男性は「バス路線があれば大丈夫じゃないかな」と代替条件を提案している。",
        "source_url": "",
        "passage": "女性：来月引っ越すんだけど、駅から近いほうがいいかな。\n男性：通勤を考えると、やっぱり駅近のほうが楽だよ。\n女性：でも、家賃が高くなるよね。\n男性：少し遠くてもバス路線があれば大丈夫じゃないかな。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "二人は何について話していますか。",
        "option_a": "新しいスマートフォンの購入を検討していること",
        "option_b": "健康のための食生活の改善",
        "option_c": "試験勉強の計画",
        "option_d": "チームの人員配置",
        "correct_answer": "B",
        "explanation": "会話は健康を意識した食事の改善について話し合っている。",
        "source_url": "",
        "passage": "男性：最近、野菜をあまり食べていないんだよね。\n女性：それは良くないよ。バランスの良い食事は大切だから。\n男性：何から始めればいいかな。\n女性：まずは毎食サラダを一品加えるだけでも違うと思うよ。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "女性が勧めている改善策はどれですか。",
        "option_a": "毎朝ジョギングをすること",
        "option_b": "肉食をやめること",
        "option_c": "毎食サラダを一品加えること",
        "option_d": "栄養補助食品を飲むこと",
        "correct_answer": "C",
        "explanation": "女性は「毎食サラダを一品加えるだけでも違うと思うよ」と具体的なアドバイスをしている。",
        "source_url": "",
        "passage": "男性：最近、野菜をあまり食べていないんだよね。\n女性：それは良くないよ。バランスの良い食事は大切だから。\n男性：何から始めればいいかな。\n女性：まずは毎食サラダを一品加えるだけでも違うと思うよ。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "男性の悩みは何ですか。",
        "option_a": "睡眠が十分に取れていないこと",
        "option_b": "野菜をあまり食べていないこと",
        "option_c": "運動する時間がないこと",
        "option_d": "体重が増えすぎていること",
        "correct_answer": "B",
        "explanation": "男性は「最近、野菜をあまり食べていないんだよね」と自分の問題を話している。",
        "source_url": "",
        "passage": "男性：最近、野菜をあまり食べていないんだよね。\n女性：それは良くないよ。バランスの良い食事は大切だから。\n男性：何から始めればいいかな。\n女性：まずは毎食サラダを一品加えるだけでも違うと思うよ。",
    },
    {
        "level": "N2",
        "question_type": "listening",
        "is_active": False,
        "question_text": "二人の会話から分かることは何ですか。",
        "option_a": "女性はすでにセミナーに参加したことがある",
        "option_b": "男性はセミナーへの参加を迷っている",
        "option_c": "セミナーは無料ではない",
        "option_d": "セミナーはオンラインで開催される",
        "correct_answer": "B",
        "explanation": "男性は「参加しようか迷っている」と述べており、まだ決めていないことが分かる。",
        "source_url": "",
        "passage": "男性：来月のビジネスセミナー、参加しようか迷っているんだ。\n女性：内容はどんなセミナーなの？\n男性：マーケティングの最新トレンドについてらしいよ。無料だし。\n女性：それは参加する価値がありそうだね。",
    },
]


def get_n2_questions() -> list[dict]:
    return N2_VOCAB + N2_GRAMMAR + N2_READING + N2_LISTENING + N2_EXTRA
