# JLPT N5 and N4 Practice Questions
# N5: 30 vocab + 30 grammar + 10 reading + 10 listening = 80 questions
# N4: 30 vocab + 30 grammar + 10 reading + 10 listening = 80 questions

N5_VOCAB = [
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「花」の読み方はどれですか。",
        "option_a": "はな",
        "option_b": "かな",
        "option_c": "はか",
        "option_d": "かわ",
        "correct_answer": "A",
        "explanation": "「花」は「はな」と読みます。花は植物の一部で、きれいな色があります。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「犬」の意味はどれですか。",
        "option_a": "cat",
        "option_b": "dog",
        "option_c": "bird",
        "option_d": "fish",
        "correct_answer": "B",
        "explanation": "「犬」は英語で「dog」という意味です。「いぬ」と読みます。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「駅」の読み方はどれですか。",
        "option_a": "えき",
        "option_b": "いき",
        "option_c": "おき",
        "option_d": "うき",
        "correct_answer": "A",
        "explanation": "「駅」は「えき」と読みます。電車が止まる場所です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「電車」の意味はどれですか。",
        "option_a": "バス",
        "option_b": "タクシー",
        "option_c": "電気で走る列車",
        "option_d": "自転車",
        "correct_answer": "C",
        "explanation": "「電車」は電気で動く列車のことです。「でんしゃ」と読みます。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「学校」の読み方はどれですか。",
        "option_a": "がくこう",
        "option_b": "がっこう",
        "option_c": "がくきょ",
        "option_d": "がっきょ",
        "correct_answer": "B",
        "explanation": "「学校」は「がっこう」と読みます。勉強する場所です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「病院」の読み方はどれですか。",
        "option_a": "びょいん",
        "option_b": "びょうえん",
        "option_c": "びょういん",
        "option_d": "びょうい",
        "correct_answer": "C",
        "explanation": "「病院」は「びょういん」と読みます。病気のときに行く場所です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「天気」の意味はどれですか。",
        "option_a": "気温",
        "option_b": "その日の空の様子",
        "option_c": "風",
        "option_d": "季節",
        "correct_answer": "B",
        "explanation": "「天気」はその日の空の様子（晴れ、雨、曇りなど）のことです。「てんき」と読みます。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「毎日」の読み方はどれですか。",
        "option_a": "まいにち",
        "option_b": "まいひ",
        "option_c": "まいじつ",
        "option_d": "まいたい",
        "correct_answer": "A",
        "explanation": "「毎日」は「まいにち」と読みます。every dayという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「友達」の読み方はどれですか。",
        "option_a": "ゆうたち",
        "option_b": "とうたち",
        "option_c": "ともたち",
        "option_d": "とうだち",
        "correct_answer": "C",
        "explanation": "「友達」は「ともだち」と読みます。仲のよい人のことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「図書館」の読み方はどれですか。",
        "option_a": "としょかん",
        "option_b": "としょくかん",
        "option_c": "とうしょかん",
        "option_d": "ずしょかん",
        "correct_answer": "A",
        "explanation": "「図書館」は「としょかん」と読みます。本を読んだり借りたりできる場所です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「魚」の読み方はどれですか。",
        "option_a": "とり",
        "option_b": "さかな",
        "option_c": "にく",
        "option_d": "むし",
        "correct_answer": "B",
        "explanation": "「魚」は「さかな」と読みます。水の中に住む生き物です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「新聞」の意味はどれですか。",
        "option_a": "雑誌",
        "option_b": "本",
        "option_c": "ニュースが書いてある紙",
        "option_d": "手紙",
        "correct_answer": "C",
        "explanation": "「新聞」はニュースや情報が書いてある紙のことです。「しんぶん」と読みます。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「銀行」の読み方はどれですか。",
        "option_a": "ぎんこ",
        "option_b": "ぎんこう",
        "option_c": "きんこ",
        "option_d": "きんこう",
        "correct_answer": "B",
        "explanation": "「銀行」は「ぎんこう」と読みます。お金を預けたり引き出したりできる場所です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「飲む」の意味はどれですか。",
        "option_a": "食べる",
        "option_b": "液体を口に入れる",
        "option_c": "料理する",
        "option_d": "話す",
        "correct_answer": "B",
        "explanation": "「飲む」は液体を口に入れることです。「のむ」と読みます。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「読む」の意味はどれですか。",
        "option_a": "書く",
        "option_b": "見る",
        "option_c": "文字を理解する",
        "option_d": "聞く",
        "correct_answer": "C",
        "explanation": "「読む」は文字を見て内容を理解することです。「よむ」と読みます。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「高い」の反対はどれですか。",
        "option_a": "長い",
        "option_b": "低い",
        "option_c": "広い",
        "option_d": "重い",
        "correct_answer": "B",
        "explanation": "「高い」の反対は「低い（ひくい）」です。値段についても使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「寒い」の読み方はどれですか。",
        "option_a": "さむい",
        "option_b": "つめたい",
        "option_c": "すずしい",
        "option_d": "ひやい",
        "correct_answer": "A",
        "explanation": "「寒い」は「さむい」と読みます。気温が低くて体が冷える感じを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「来年」の意味はどれですか。",
        "option_a": "去年",
        "option_b": "今年",
        "option_c": "next year",
        "option_d": "先年",
        "correct_answer": "C",
        "explanation": "「来年」は「らいねん」と読み、next yearという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「何時」の読み方はどれですか。",
        "option_a": "なんじ",
        "option_b": "なにじ",
        "option_c": "いつじ",
        "option_d": "どのじ",
        "correct_answer": "A",
        "explanation": "「何時」は「なんじ」と読みます。時刻を尋ねるときに使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「午後」の意味はどれですか。",
        "option_a": "朝",
        "option_b": "昼の前",
        "option_c": "正午から夜まで",
        "option_d": "夜",
        "correct_answer": "C",
        "explanation": "「午後」は「ごご」と読み、正午（12時）から夜までの時間を指します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「小さい」の読み方はどれですか。",
        "option_a": "おおきい",
        "option_b": "ちいさい",
        "option_c": "ちさい",
        "option_d": "こさい",
        "correct_answer": "B",
        "explanation": "「小さい」は「ちいさい」と読みます。サイズが少ないことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「肉」の読み方はどれですか。",
        "option_a": "にく",
        "option_b": "さかな",
        "option_c": "やさい",
        "option_d": "くだもの",
        "correct_answer": "A",
        "explanation": "「肉」は「にく」と読みます。動物の体から取れる食べ物です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「空港」の意味はどれですか。",
        "option_a": "駅",
        "option_b": "飛行機が離着陸する場所",
        "option_c": "港",
        "option_d": "バスターミナル",
        "correct_answer": "B",
        "explanation": "「空港」は「くうこう」と読み、飛行機が離着陸する場所です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「部屋」の読み方はどれですか。",
        "option_a": "へや",
        "option_b": "べや",
        "option_c": "ぶや",
        "option_d": "ほや",
        "correct_answer": "A",
        "explanation": "「部屋」は「へや」と読みます。建物の中の一つの空間のことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「先生」の意味はどれですか。",
        "option_a": "学生",
        "option_b": "教える人",
        "option_c": "医者",
        "option_d": "会社員",
        "correct_answer": "B",
        "explanation": "「先生」は「せんせい」と読み、教える人のことです。医者や弁護士にも使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「春」の読み方はどれですか。",
        "option_a": "なつ",
        "option_b": "あき",
        "option_c": "はる",
        "option_d": "ふゆ",
        "correct_answer": "C",
        "explanation": "「春」は「はる」と読みます。3月から5月ごろの温かい季節です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「買う」の意味はどれですか。",
        "option_a": "売る",
        "option_b": "お金を払って手に入れる",
        "option_c": "借りる",
        "option_d": "もらう",
        "correct_answer": "B",
        "explanation": "「買う」は「かう」と読み、お金を払って商品を手に入れることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「兄」の読み方はどれですか。",
        "option_a": "あに",
        "option_b": "おとうと",
        "option_c": "いもうと",
        "option_d": "あね",
        "correct_answer": "A",
        "explanation": "「兄」は「あに」と読みます。自分より年上の男の兄弟のことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「古い」の意味はどれですか。",
        "option_a": "新しい",
        "option_b": "長い時間が経っている",
        "option_c": "遠い",
        "option_d": "重い",
        "correct_answer": "B",
        "explanation": "「古い」は「ふるい」と読み、長い時間が経っていることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "vocabulary",
        "question_text": "「外国」の読み方はどれですか。",
        "option_a": "がいこく",
        "option_b": "そとくに",
        "option_c": "がいにく",
        "option_d": "そとこく",
        "correct_answer": "A",
        "explanation": "「外国」は「がいこく」と読みます。自分の国以外の国のことです。",
        "source_url": "",
        "passage": "",
    },
]

N5_GRAMMAR = [
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "田中さんは今、本を（　）います。",
        "option_a": "読んで",
        "option_b": "読み",
        "option_c": "読む",
        "option_d": "読ま",
        "correct_answer": "A",
        "explanation": "「〜ています」は現在進行中の動作を表します。「読む」のて形は「読んで」です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "一緒に映画を見（　）か。",
        "option_a": "ません",
        "option_b": "ましょう",
        "option_c": "ませんでした",
        "option_d": "ませんか",
        "correct_answer": "D",
        "explanation": "「〜ませんか」は相手を誘う表現です。「一緒に映画を見ませんか」で「一緒に映画を見ませんか」という誘いになります。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "ご飯を食べ（　）、出かけました。",
        "option_a": "て",
        "option_b": "で",
        "option_c": "に",
        "option_d": "が",
        "correct_answer": "A",
        "explanation": "「〜て、〜」は動作の順序を表します。「食べて、出かける」で食べた後に出かけるという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "学校（　）行きます。",
        "option_a": "を",
        "option_b": "が",
        "option_c": "に",
        "option_d": "は",
        "correct_answer": "C",
        "explanation": "移動の目的地には「に」を使います。「学校に行く」で学校へ向かうという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "私（　）学生です。",
        "option_a": "が",
        "option_b": "は",
        "option_c": "を",
        "option_d": "に",
        "correct_answer": "B",
        "explanation": "「は」は話題を示す助詞です。「私は学生です」で自分が学生であることを述べています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "今日は寒い（　）、コートを着ます。",
        "option_a": "が",
        "option_b": "から",
        "option_c": "で",
        "option_d": "けど",
        "correct_answer": "B",
        "explanation": "「〜から」は理由を表します。「寒いからコートを着る」で寒さが理由でコートを着るという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "コーヒー（　）紅茶、どちらが好きですか。",
        "option_a": "か",
        "option_b": "と",
        "option_c": "や",
        "option_d": "も",
        "correct_answer": "B",
        "explanation": "「AとB、どちら」は二つのものを比べるときに使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "公園（　）走ります。",
        "option_a": "に",
        "option_b": "が",
        "option_c": "で",
        "option_d": "を",
        "correct_answer": "D",
        "explanation": "移動する経路には「を」を使います。「公園を走る」で公園の中を走るという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "明日、早く起き（　）。",
        "option_a": "ましょう",
        "option_b": "ませんか",
        "option_c": "ます",
        "option_d": "ません",
        "correct_answer": "A",
        "explanation": "「〜ましょう」は提案や勧誘を表します。自分も含めて「〜しよう」という意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "この本は面白い（　）、難しいです。",
        "option_a": "から",
        "option_b": "が",
        "option_c": "で",
        "option_d": "に",
        "correct_answer": "B",
        "explanation": "「〜が、〜」は逆接を表します。「面白いが、難しい」で面白いけれど難しいという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "水を（　）ください。",
        "option_a": "飲んで",
        "option_b": "飲み",
        "option_c": "飲む",
        "option_d": "飲んだ",
        "correct_answer": "A",
        "explanation": "「〜てください」は依頼を表します。「飲む」のて形は「飲んで」です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "あの人（　）だれですか。",
        "option_a": "は",
        "option_b": "が",
        "option_c": "を",
        "option_d": "に",
        "correct_answer": "A",
        "explanation": "「〜はだれですか」は人を尋ねるときの表現です。「は」は話題を示します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "テレビ（　）見ながら、ご飯を食べます。",
        "option_a": "は",
        "option_b": "が",
        "option_c": "を",
        "option_d": "で",
        "correct_answer": "C",
        "explanation": "「〜を見る」のように、動詞の目的語には「を」を使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "私の妹（　）12歳です。",
        "option_a": "が",
        "option_b": "は",
        "option_c": "も",
        "option_d": "に",
        "correct_answer": "B",
        "explanation": "「〜は〜です」は情報を述べるときの基本的な文型です。「は」は話題を示します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "ペン（　）鉛筆（　）あります。",
        "option_a": "と、が",
        "option_b": "と、は",
        "option_c": "や、で",
        "option_d": "が、を",
        "correct_answer": "A",
        "explanation": "「AとBがある」は複数のものが存在することを表します。「と」は並列、「が」は存在の主語を示します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "昨日、映画（　）見ました。",
        "option_a": "が",
        "option_b": "は",
        "option_c": "に",
        "option_d": "を",
        "correct_answer": "D",
        "explanation": "「映画を見る」のように、動詞「見る」の目的語には「を」を使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "鈴木さん（　）来ましたか。",
        "option_a": "は",
        "option_b": "が",
        "option_c": "に",
        "option_d": "を",
        "correct_answer": "B",
        "explanation": "疑問文で主語を尋ねるときや焦点を当てるときに「が」を使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "スーパー（　）買い物をします。",
        "option_a": "に",
        "option_b": "で",
        "option_c": "を",
        "option_d": "が",
        "correct_answer": "B",
        "explanation": "動作が行われる場所には「で」を使います。「スーパーで買い物をする」で買い物する場所がスーパーです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "何か食べ（　）ですか。",
        "option_a": "たい",
        "option_b": "てい",
        "option_c": "ます",
        "option_d": "ない",
        "correct_answer": "A",
        "explanation": "「〜たい」は望みや希望を表します。「食べたい」で食べることを望んでいるという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "もっと ゆっくり 話し（　）ください。",
        "option_a": "て",
        "option_b": "で",
        "option_c": "に",
        "option_d": "が",
        "correct_answer": "A",
        "explanation": "「〜てください」は依頼を表します。「話して」は「話す」のて形です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "図書館では静かに（　）ください。",
        "option_a": "し",
        "option_b": "して",
        "option_c": "する",
        "option_d": "した",
        "correct_answer": "B",
        "explanation": "「〜てください」は依頼を表します。「静かにして」は「静かにする」のて形です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "あなた（　）名前は何ですか。",
        "option_a": "の",
        "option_b": "が",
        "option_c": "は",
        "option_d": "を",
        "correct_answer": "A",
        "explanation": "「〜の〜」は所有や所属を表します。「あなたの名前」であなたが持っている名前という意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "山田さんは背（　）高いです。",
        "option_a": "は",
        "option_b": "が",
        "option_c": "を",
        "option_d": "に",
        "correct_answer": "B",
        "explanation": "身体的特徴を表すとき「〜が〜い」を使います。「背が高い」は「が」を使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "東京（　）大阪まで、新幹線で2時間かかります。",
        "option_a": "から",
        "option_b": "まで",
        "option_c": "より",
        "option_d": "で",
        "correct_answer": "A",
        "explanation": "「〜から〜まで」は起点と終点を示します。「東京から」で東京を出発点とする意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "この映画は子供（　）大人（　）楽しめます。",
        "option_a": "も、も",
        "option_b": "は、は",
        "option_c": "と、と",
        "option_d": "や、や",
        "correct_answer": "A",
        "explanation": "「〜も〜も」は両方を含む表現です。「子供も大人も」で子供と大人の両方という意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "この仕事を（　）のは難しいです。",
        "option_a": "する",
        "option_b": "して",
        "option_c": "し",
        "option_d": "した",
        "correct_answer": "A",
        "explanation": "「〜のは」は動詞を名詞化します。「するのは難しい」でその動作が難しいという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "明日、雨（　）降るでしょう。",
        "option_a": "が",
        "option_b": "は",
        "option_c": "を",
        "option_d": "で",
        "correct_answer": "A",
        "explanation": "「雨が降る」は雨が降ることを表す定型表現です。主語には「が」を使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "電気を（　）から、出かけます。",
        "option_a": "消えて",
        "option_b": "消して",
        "option_c": "消す",
        "option_d": "消した",
        "correct_answer": "B",
        "explanation": "「〜てから」は前の動作が終わってから次の動作をすることを表します。「消して」は「消す」のて形です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "日本語（　）上手ですね。",
        "option_a": "を",
        "option_b": "は",
        "option_c": "に",
        "option_d": "が",
        "correct_answer": "D",
        "explanation": "「〜が上手だ」は技能を表す定型表現です。「日本語が上手」という形で使います。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N5",
        "question_type": "grammar",
        "question_text": "駅の前（　）待っています。",
        "option_a": "で",
        "option_b": "に",
        "option_c": "を",
        "option_d": "が",
        "correct_answer": "B",
        "explanation": "「〜に待つ」は場所を示します。「待つ」などの状態動詞の場所には「に」を使います。",
        "source_url": "",
        "passage": "",
    },
]

N5_READING = [
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この文章によると、山田さんは何時に起きますか。",
        "option_a": "6時",
        "option_b": "7時",
        "option_c": "8時",
        "option_d": "9時",
        "correct_answer": "B",
        "explanation": "文章に「山田さんは毎朝7時に起きます」と書いてあります。",
        "source_url": "",
        "passage": "山田さんは毎朝7時に起きます。起きてから、シャワーを浴びて、朝ご飯を食べます。朝ご飯はパンとコーヒーです。8時に家を出て、電車で会社に行きます。会社は9時に始まります。",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この文章によると、田中さんの趣味はどれですか。",
        "option_a": "映画を見ること",
        "option_b": "音楽を聴くこと",
        "option_c": "本を読むこと",
        "option_d": "スポーツをすること",
        "correct_answer": "C",
        "explanation": "文章に「田中さんの趣味は本を読むことです」と書いてあります。",
        "source_url": "",
        "passage": "田中さんの趣味は本を読むことです。毎週末、図書館に行って、本を借ります。好きなジャンルは歴史の本です。一週間に3冊くらい読みます。図書館の人に顔を覚えられています。",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この文章によると、このレストランは何曜日が休みですか。",
        "option_a": "土曜日",
        "option_b": "日曜日",
        "option_c": "月曜日",
        "option_d": "火曜日",
        "correct_answer": "C",
        "explanation": "「定休日は月曜日です」と書いてあります。",
        "source_url": "",
        "passage": "このレストランは毎日11時から21時まで開いています。定休日は月曜日です。ランチは11時から14時まで、ディナーは17時から21時までです。予約は電話でできます。駐車場は10台あります。",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この手紙によると、鈴木さんはどこに住んでいますか。",
        "option_a": "東京",
        "option_b": "大阪",
        "option_c": "名古屋",
        "option_d": "京都",
        "correct_answer": "A",
        "explanation": "手紙に「私は今、東京に住んでいます」と書いてあります。",
        "source_url": "",
        "passage": "山本さんへ、お元気ですか。私は今、東京に住んでいます。東京は大きくて、人が多いですが、とても楽しいです。来月、大阪に行く予定があります。その時に会いたいです。鈴木より",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この掲示によると、プールは何月から使えますか。",
        "option_a": "4月",
        "option_b": "5月",
        "option_c": "6月",
        "option_d": "7月",
        "correct_answer": "C",
        "explanation": "「6月1日からプールが使えます」と書いてあります。",
        "source_url": "",
        "passage": "お知らせ：6月1日からプールが使えます。利用時間は午前9時から午後6時までです。利用する方は会員証を持ってきてください。子供は一人では入れません。大人と一緒に来てください。",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この文章によると、犬の名前は何ですか。",
        "option_a": "ポチ",
        "option_b": "タロ",
        "option_c": "シロ",
        "option_d": "クロ",
        "correct_answer": "B",
        "explanation": "文章に「うちの犬の名前はタロです」と書いてあります。",
        "source_url": "",
        "passage": "うちの犬の名前はタロです。タロは3歳で、毎日元気に走り回っています。毎朝、公園で散歩します。タロはボールで遊ぶのが好きです。家族みんながタロを大切にしています。",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この文章によると、今日の天気はどうですか。",
        "option_a": "晴れ",
        "option_b": "雨",
        "option_c": "曇り",
        "option_d": "雪",
        "correct_answer": "C",
        "explanation": "文章に「今日は曇りです」と書いてあります。",
        "source_url": "",
        "passage": "今日は曇りです。昨日は晴れでとてもよい天気でしたが、今日は雲が多いです。気温は15度で、少し寒いです。明日は雨が降る予報です。傘を持っていった方がいいでしょう。",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この文章によると、花子さんは何語を勉強していますか。",
        "option_a": "英語",
        "option_b": "中国語",
        "option_c": "フランス語",
        "option_d": "スペイン語",
        "correct_answer": "C",
        "explanation": "「花子さんはフランス語を勉強しています」と書いてあります。",
        "source_url": "",
        "passage": "花子さんはフランス語を勉強しています。毎週火曜日と木曜日に語学学校に通っています。将来、フランスで働きたいと思っています。フランスの映画もよく見ます。今年の夏にフランスに行く予定です。",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この文章によると、駅から学校まで何分かかりますか。",
        "option_a": "5分",
        "option_b": "10分",
        "option_c": "15分",
        "option_d": "20分",
        "correct_answer": "B",
        "explanation": "「駅から学校まで歩いて10分かかります」と書いてあります。",
        "source_url": "",
        "passage": "私の学校は駅の近くにあります。駅から学校まで歩いて10分かかります。学校の前にコンビニがあります。学校には食堂があって、昼ご飯を食べることができます。放課後はクラブ活動があります。",
    },
    {
        "level": "N5",
        "question_type": "reading",
        "question_text": "この文章によると、誰が料理を作りましたか。",
        "option_a": "お母さん",
        "option_b": "お父さん",
        "option_c": "お兄さん",
        "option_d": "私",
        "correct_answer": "D",
        "explanation": "「私が料理を作りました」と書いてあります。",
        "source_url": "",
        "passage": "今日は家族の誕生日パーティーがありました。私が料理を作りました。カレーライスとサラダを作りました。お母さんはケーキを買ってきました。みんなとても喜んでくれて、うれしかったです。",
    },
]

N5_LISTENING = [
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、二人はどこで会いますか。",
        "option_a": "駅",
        "option_b": "図書館",
        "option_c": "公園",
        "option_d": "学校",
        "correct_answer": "A",
        "explanation": "男の人が「駅で待っています」と言っています。",
        "source_url": "",
        "passage": "女：もしもし、今どこですか。\n男：今、駅にいます。\n女：あ、そうですか。私はもう少しかかります。\n男：大丈夫です。駅で待っています。\n女：すみません。すぐ行きます。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、男の人は何を注文しますか。",
        "option_a": "コーヒー",
        "option_b": "紅茶",
        "option_c": "ジュース",
        "option_d": "水",
        "correct_answer": "B",
        "explanation": "男の人は「紅茶をください」と言っています。",
        "source_url": "",
        "passage": "店員：いらっしゃいませ。ご注文はお決まりですか。\n男：えーと、コーヒーはありますか。\n店員：はい、ございます。\n男：でも、やっぱり紅茶をください。\n店員：かしこまりました。少々お待ちください。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "このアナウンスによると、電車はいつ来ますか。",
        "option_a": "3分後",
        "option_b": "5分後",
        "option_c": "10分後",
        "option_d": "15分後",
        "correct_answer": "B",
        "explanation": "アナウンスで「5分後に電車が参ります」と言っています。",
        "source_url": "",
        "passage": "駅のアナウンス：お待ちのお客様にお知らせします。ただいま、電車が少し遅れております。次の電車は5分後に参ります。大変ご迷惑をおかけして申し訳ございません。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、女の人はどこに行きますか。",
        "option_a": "病院",
        "option_b": "スーパー",
        "option_c": "学校",
        "option_d": "映画館",
        "correct_answer": "A",
        "explanation": "女の人は「病院に行かなければなりません」と言っています。",
        "source_url": "",
        "passage": "男：今日、一緒に買い物しませんか。\n女：すみません、今日はちょっと。\n男：どうしたんですか。\n女：実は、病院に行かなければなりません。\n男：そうですか。大丈夫ですか。\n女：ええ、定期検診ですから。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、二人は何を食べますか。",
        "option_a": "すし",
        "option_b": "ラーメン",
        "option_c": "カレー",
        "option_d": "ピザ",
        "correct_answer": "C",
        "explanation": "女の人が「カレーにしましょう」と提案し、男の人が「いいですね」と同意しています。",
        "source_url": "",
        "passage": "女：お昼、何食べる？\n男：うーん、ラーメンはどう？\n女：ラーメンは昨日食べたよ。\n男：じゃあ、すしは？\n女：カレーにしましょうよ。\n男：いいですね。そうしましょう。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、宿題はいつまでですか。",
        "option_a": "今日",
        "option_b": "明日",
        "option_c": "来週",
        "option_d": "今週金曜日",
        "correct_answer": "B",
        "explanation": "先生が「明日までに出してください」と言っています。",
        "source_url": "",
        "passage": "先生：みなさん、今日の宿題を覚えていますか。\n学生：はい、作文ですね。\n先生：そうです。明日までに出してください。\n学生：先生、どのくらい書けばいいですか。\n先生：200字以上書いてください。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、図書館は何時に閉まりますか。",
        "option_a": "5時",
        "option_b": "6時",
        "option_c": "7時",
        "option_d": "8時",
        "correct_answer": "B",
        "explanation": "図書館のスタッフが「今日は6時に閉館します」と言っています。",
        "source_url": "",
        "passage": "スタッフ：お客様、もうすぐ閉館時間です。\n客：あ、何時に閉まりますか。\nスタッフ：今日は6時に閉館します。あと15分です。\n客：わかりました。本を返して帰ります。\nスタッフ：ありがとうございました。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "このアナウンスによると、何が見つかりましたか。",
        "option_a": "かぎ",
        "option_b": "財布",
        "option_c": "かばん",
        "option_d": "帽子",
        "correct_answer": "B",
        "explanation": "アナウンスで「財布が見つかりました」と言っています。",
        "source_url": "",
        "passage": "デパートのアナウンス：お客様にお知らせします。只今、1階のサービスカウンターで、財布が見つかりました。黒い財布です。お心当たりのお客様は、1階のサービスカウンターまでお越しください。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、男の人は今何をしていますか。",
        "option_a": "ご飯を食べている",
        "option_b": "テレビを見ている",
        "option_c": "勉強している",
        "option_d": "寝ている",
        "correct_answer": "C",
        "explanation": "男の人は「今、テストの勉強をしています」と言っています。",
        "source_url": "",
        "passage": "女：ねえ、一緒に映画見ない？\n男：ごめん、今忙しいんだ。\n女：何してるの？\n男：今、テストの勉強をしています。明日テストがあるから。\n女：そうか。じゃあ、また今度ね。\n男：うん、ごめんね。",
    },
    {
        "level": "N5",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、女の人はどんなシャツを探していますか。",
        "option_a": "白いシャツ",
        "option_b": "青いシャツ",
        "option_c": "赤いシャツ",
        "option_d": "黄色いシャツ",
        "correct_answer": "B",
        "explanation": "女の人が「青いシャツを探しています」と言っています。",
        "source_url": "",
        "passage": "店員：いらっしゃいませ。何かお探しですか。\n客：ええ、シャツを探しています。\n店員：どんなシャツをお探しですか。\n客：青いシャツがほしいんですが。\n店員：かしこまりました。こちらにございます。",
    },
]

N4_VOCAB = [
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「経験」の読み方はどれですか。",
        "option_a": "けいけん",
        "option_b": "けいかん",
        "option_c": "きょうけん",
        "option_d": "きょうかん",
        "correct_answer": "A",
        "explanation": "「経験」は「けいけん」と読みます。実際に体験したことを指します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「集める」の意味はどれですか。",
        "option_a": "ばらばらにする",
        "option_b": "一か所に多くのものを持ってくる",
        "option_c": "捨てる",
        "option_d": "送る",
        "correct_answer": "B",
        "explanation": "「集める」は「あつめる」と読み、ばらばらなものを一か所に集合させることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「親切」の読み方はどれですか。",
        "option_a": "しんせつ",
        "option_b": "しんさつ",
        "option_c": "しんきつ",
        "option_d": "しんさい",
        "correct_answer": "A",
        "explanation": "「親切」は「しんせつ」と読みます。他の人に対して優しく思いやりがあることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「説明」の意味はどれですか。",
        "option_a": "質問する",
        "option_b": "わかるように話す",
        "option_c": "翻訳する",
        "option_d": "紹介する",
        "correct_answer": "B",
        "explanation": "「説明」は「せつめい」と読み、内容をわかりやすく話したり書いたりすることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「安全」の読み方はどれですか。",
        "option_a": "あんぜん",
        "option_b": "あんさい",
        "option_c": "あんぜい",
        "option_d": "あんぜん",
        "correct_answer": "A",
        "explanation": "「安全」は「あんぜん」と読みます。危険がなく、安心できる状態のことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「用意する」の意味はどれですか。",
        "option_a": "使う",
        "option_b": "準備する",
        "option_c": "終わらせる",
        "option_d": "忘れる",
        "correct_answer": "B",
        "explanation": "「用意する」は「ようい」と読み、必要なものを準備することです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「失敗」の読み方はどれですか。",
        "option_a": "しっぱい",
        "option_b": "しつはい",
        "option_c": "しっぱ",
        "option_d": "しつぱい",
        "correct_answer": "A",
        "explanation": "「失敗」は「しっぱい」と読みます。うまくいかないことです。反対語は「成功」です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「成長」の意味はどれですか。",
        "option_a": "小さくなること",
        "option_b": "変わらないこと",
        "option_c": "だんだん大きくなること",
        "option_d": "壊れること",
        "correct_answer": "C",
        "explanation": "「成長」は「せいちょう」と読み、体や能力などがだんだん大きくなることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「迷う」の意味はどれですか。",
        "option_a": "決める",
        "option_b": "どうすればいいかわからない",
        "option_c": "急ぐ",
        "option_d": "走る",
        "correct_answer": "B",
        "explanation": "「迷う」は「まよう」と読み、どうすればよいかわからなくて困ることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「思い出す」の意味はどれですか。",
        "option_a": "忘れる",
        "option_b": "覚えていることを再び意識する",
        "option_c": "想像する",
        "option_d": "考える",
        "correct_answer": "B",
        "explanation": "「思い出す」は「おもいだす」と読み、忘れていたことを再び思い浮かべることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「予約」の読み方はどれですか。",
        "option_a": "よやく",
        "option_b": "よやっ",
        "option_c": "よがく",
        "option_d": "よかく",
        "correct_answer": "A",
        "explanation": "「予約」は「よやく」と読みます。前もって場所や品物を確保することです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「注意」の意味はどれですか。",
        "option_a": "リラックスすること",
        "option_b": "気をつけること",
        "option_c": "楽しむこと",
        "option_d": "休むこと",
        "correct_answer": "B",
        "explanation": "「注意」は「ちゅうい」と読み、気をつけることや気をつけるよう伝えることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「習慣」の読み方はどれですか。",
        "option_a": "しゅかん",
        "option_b": "しゅうかん",
        "option_c": "しゅうかい",
        "option_d": "しゅかい",
        "correct_answer": "B",
        "explanation": "「習慣」は「しゅうかん」と読みます。毎日繰り返して行うことで身についた行動のことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「断る」の意味はどれですか。",
        "option_a": "同意する",
        "option_b": "頼む",
        "option_c": "はっきりと受け入れないと言う",
        "option_d": "忘れる",
        "correct_answer": "C",
        "explanation": "「断る」は「ことわる」と読み、頼まれたことや誘いをはっきり受け入れないと言うことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「寂しい」の読み方はどれですか。",
        "option_a": "さみしい",
        "option_b": "さびしい",
        "option_c": "さましい",
        "option_d": "さむしい",
        "correct_answer": "B",
        "explanation": "「寂しい」は「さびしい」（または「さみしい」）と読みます。一人でいて物足りなく感じる状態です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「増える」の反対語はどれですか。",
        "option_a": "伸びる",
        "option_b": "広がる",
        "option_c": "減る",
        "option_d": "重くなる",
        "correct_answer": "C",
        "explanation": "「増える（ふえる）」の反対語は「減る（へる）」です。数や量が少なくなることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「詳しい」の意味はどれですか。",
        "option_a": "簡単な",
        "option_b": "細かいことまでよく知っている",
        "option_c": "新しい",
        "option_d": "正しい",
        "correct_answer": "B",
        "explanation": "「詳しい」は「くわしい」と読み、細かいことまでよく知っていることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「確認」の読み方はどれですか。",
        "option_a": "かくにん",
        "option_b": "かくにい",
        "option_c": "かくねん",
        "option_d": "かくかん",
        "correct_answer": "A",
        "explanation": "「確認」は「かくにん」と読みます。正しいかどうかを確かめることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「慌てる」の意味はどれですか。",
        "option_a": "落ち着く",
        "option_b": "急いでパニックになる",
        "option_c": "怒る",
        "option_d": "喜ぶ",
        "correct_answer": "B",
        "explanation": "「慌てる」は「あわてる」と読み、予期せぬことが起きてパニックになることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「目的」の読み方はどれですか。",
        "option_a": "もくひ",
        "option_b": "もくてき",
        "option_c": "めてき",
        "option_d": "めひき",
        "correct_answer": "B",
        "explanation": "「目的」は「もくてき」と読みます。目標や狙いのことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「返事」の意味はどれですか。",
        "option_a": "質問する",
        "option_b": "呼びかけに対して答える",
        "option_c": "無視する",
        "option_d": "送る",
        "correct_answer": "B",
        "explanation": "「返事」は「へんじ」と読み、呼びかけや質問に対して答えることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「生活」の読み方はどれですか。",
        "option_a": "せいかつ",
        "option_b": "せいがつ",
        "option_c": "せいかく",
        "option_d": "せいがく",
        "correct_answer": "A",
        "explanation": "「生活」は「せいかつ」と読みます。日常の暮らしのことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「笑う」の反対語はどれですか。",
        "option_a": "叫ぶ",
        "option_b": "泣く",
        "option_c": "話す",
        "option_d": "黙る",
        "correct_answer": "B",
        "explanation": "「笑う（わらう）」の反対語は「泣く（なく）」です。悲しみや痛みで涙を流すことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「場合」の読み方はどれですか。",
        "option_a": "ばあい",
        "option_b": "ばいあい",
        "option_c": "ばおい",
        "option_d": "ばがい",
        "correct_answer": "A",
        "explanation": "「場合」は「ばあい」と読みます。ある状況や条件のことを指します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「乗り換える」の意味はどれですか。",
        "option_a": "電車に乗る",
        "option_b": "別の交通機関に移ること",
        "option_c": "降りる",
        "option_d": "乗り遅れる",
        "correct_answer": "B",
        "explanation": "「乗り換える」は「のりかえる」と読み、ある電車やバスから別の電車やバスに移ることです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「嬉しい」の読み方はどれですか。",
        "option_a": "かなしい",
        "option_b": "さみしい",
        "option_c": "うれしい",
        "option_d": "くるしい",
        "correct_answer": "C",
        "explanation": "「嬉しい」は「うれしい」と読みます。喜ばしくて気持ちが晴れやかなことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「正直」の意味はどれですか。",
        "option_a": "嘘をつくこと",
        "option_b": "事実をそのまま言うこと",
        "option_c": "意地悪なこと",
        "option_d": "間違えること",
        "correct_answer": "B",
        "explanation": "「正直」は「しょうじき」と読み、嘘をつかずに事実をそのまま話すことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「複雑」の読み方はどれですか。",
        "option_a": "ふくざつ",
        "option_b": "ふくさつ",
        "option_c": "ふっざつ",
        "option_d": "ふくざい",
        "correct_answer": "A",
        "explanation": "「複雑」は「ふくざつ」と読みます。いろいろな要素が絡み合っていて単純でないことです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「気づく」の意味はどれですか。",
        "option_a": "忘れる",
        "option_b": "意識していなかったことを認識する",
        "option_c": "考える",
        "option_d": "眠る",
        "correct_answer": "B",
        "explanation": "「気づく」は「きづく」と読み、それまで意識していなかったことを突然理解することです。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "vocabulary",
        "question_text": "「消える」の意味はどれですか。",
        "option_a": "現れる",
        "option_b": "見えなくなる",
        "option_c": "増える",
        "option_d": "燃える",
        "correct_answer": "B",
        "explanation": "「消える」は「きえる」と読み、それまであったものが見えなくなることです。",
        "source_url": "",
        "passage": "",
    },
]

N4_GRAMMAR = [
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "ここでタバコを吸っ（　）いけません。",
        "option_a": "ても",
        "option_b": "ては",
        "option_c": "てを",
        "option_d": "てに",
        "correct_answer": "B",
        "explanation": "「〜てはいけない」は禁止を表す表現です。「タバコを吸ってはいけない」で吸うことを禁止しています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "ここに座っ（　）いいですか。",
        "option_a": "ては",
        "option_b": "ても",
        "option_c": "てに",
        "option_d": "てを",
        "correct_answer": "B",
        "explanation": "「〜てもいいですか」は許可を求める表現です。「座ってもいいですか」で座ることの許可を求めています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "週末は買い物し（　）映画を見（　）します。",
        "option_a": "たり、たり",
        "option_b": "て、て",
        "option_c": "り、り",
        "option_d": "し、し",
        "correct_answer": "A",
        "explanation": "「〜たり〜たりする」は複数の動作を並列して表す表現です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "健康（　）ために、毎日運動しています。",
        "option_a": "に",
        "option_b": "の",
        "option_c": "を",
        "option_d": "が",
        "correct_answer": "B",
        "explanation": "「〜のために」は目的を表します。「健康のために」で健康を目的として運動することを示します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "音楽を聴き（　）、勉強します。",
        "option_a": "ながら",
        "option_b": "てから",
        "option_c": "ながら",
        "option_d": "ために",
        "correct_answer": "A",
        "explanation": "「〜ながら」は二つの動作を同時に行うことを表します。「聴きながら勉強する」で聴きつつ勉強するという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "このケーキはおいし（　）そうです。",
        "option_a": "い",
        "option_b": "く",
        "option_c": "さ",
        "option_d": "で",
        "correct_answer": "A",
        "explanation": "「〜そうだ」は見た目からの判断を表します。形容詞の場合、「おいしい」の語幹「おいし」に「そうだ」をつけます。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "雨が降れ（　）、試合は中止です。",
        "option_a": "たら",
        "option_b": "ば",
        "option_c": "と",
        "option_d": "なら",
        "correct_answer": "B",
        "explanation": "「〜ば〜」は条件を表す仮定形です。「降れば」で「降ったら」という意味になります。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "テストが終わっ（　）、遊びに行こう。",
        "option_a": "てから",
        "option_b": "ながら",
        "option_c": "たり",
        "option_d": "ために",
        "correct_answer": "A",
        "explanation": "「〜てから」は前の動作が終わった後に次の動作をすることを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "このドアは（　）ません。",
        "option_a": "開け",
        "option_b": "開けられ",
        "option_c": "開ける",
        "option_d": "開けて",
        "correct_answer": "B",
        "explanation": "「〜られない」は可能の否定形です。「開けられません」でドアを開けることができないという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "彼は毎朝ジョギングする（　）。",
        "option_a": "そうです",
        "option_b": "ようです",
        "option_c": "らしいです",
        "option_d": "はずです",
        "correct_answer": "A",
        "explanation": "「〜そうだ」は伝聞を表します。「〜するそうだ」で誰かから聞いたことを伝える表現です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "彼女は歌手に（　）たいと思っています。",
        "option_a": "なり",
        "option_b": "なる",
        "option_c": "なっ",
        "option_d": "なられ",
        "correct_answer": "A",
        "explanation": "「〜になりたい」は望みを表します。「なりたい」の前は「なり」（ます形の語幹）です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "この問題はむずかし（　）みえます。",
        "option_a": "く",
        "option_b": "い",
        "option_c": "さ",
        "option_d": "で",
        "correct_answer": "A",
        "explanation": "「〜くみえる」は外見の印象を表します。形容詞を副詞的に使うには「く」をつけます。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "宿題を忘れた（　）、先生に叱られた。",
        "option_a": "ので",
        "option_b": "のに",
        "option_c": "から",
        "option_d": "けど",
        "correct_answer": "A",
        "explanation": "「〜ので」は理由を表します。「忘れたので」で宿題を忘れたことが叱られた理由です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "もっと早く来れ（　）よかったのに。",
        "option_a": "ば",
        "option_b": "たら",
        "option_c": "て",
        "option_d": "なら",
        "correct_answer": "A",
        "explanation": "「〜ればよかった」は後悔を表す表現です。「来れば」は「来る」の仮定形です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "このパソコンは使い（　）です。",
        "option_a": "やすい",
        "option_b": "にくい",
        "option_c": "たい",
        "option_d": "そう",
        "correct_answer": "A",
        "explanation": "「〜やすい」は動作が簡単にできることを表します。「使いやすい」で使うことが簡単という意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "体の具合が悪い（　）、学校を休みました。",
        "option_a": "ので",
        "option_b": "のに",
        "option_c": "だから",
        "option_d": "けれど",
        "correct_answer": "A",
        "explanation": "「〜ので」は理由を表す接続表現です。「体が悪いので学校を休む」で体調が原因で休んだことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "彼は日本語が話せる（　）、通訳ができます。",
        "option_a": "ので",
        "option_b": "から",
        "option_c": "し",
        "option_d": "が",
        "correct_answer": "A",
        "explanation": "「〜ので〜できる」は理由と結果を表します。「話せるので通訳ができる」という論理的な因果関係を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "このテストは難し（　）て、合格できませんでした。",
        "option_a": "く",
        "option_b": "い",
        "option_c": "さ",
        "option_d": "で",
        "correct_answer": "A",
        "explanation": "形容詞を「〜て」で繋ぐときは、い形容詞は「〜くて」の形になります。「難しくて」が正しい形です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "仕事が終わる（　）すぐ帰ります。",
        "option_a": "と",
        "option_b": "たら",
        "option_c": "ば",
        "option_d": "なら",
        "correct_answer": "A",
        "explanation": "「〜と〜」は条件や自然な流れを表します。「終わると帰る」で仕事が終わったらすぐ帰るという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "あの店は安い（　）、おいしいです。",
        "option_a": "くて",
        "option_b": "けど",
        "option_c": "し",
        "option_d": "のに",
        "correct_answer": "C",
        "explanation": "「〜し〜し」は複数の理由や特徴を列挙するときに使います。「安いし、おいしいし」で二つの長所を挙げています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "先生に聞け（　）よかった。",
        "option_a": "ば",
        "option_b": "て",
        "option_c": "たら",
        "option_d": "ると",
        "correct_answer": "A",
        "explanation": "「〜ばよかった」は過去の後悔を表します。「聞けばよかった」で聞いておけばよかったという意味です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "疲れ（　）、仕事をやめることにしました。",
        "option_a": "てしまって",
        "option_b": "ながら",
        "option_c": "てから",
        "option_d": "たから",
        "correct_answer": "D",
        "explanation": "「〜たから〜した」は過去の理由を表します。「疲れたから」で疲れたことが理由だということを示します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "熱が出（　）しまいました。",
        "option_a": "て",
        "option_b": "で",
        "option_c": "に",
        "option_d": "が",
        "correct_answer": "A",
        "explanation": "「〜てしまう」は完了や後悔を表します。「出てしまいました」で熱が出てしまったことを表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "この荷物、持っ（　）もらえますか。",
        "option_a": "て",
        "option_b": "で",
        "option_c": "を",
        "option_d": "に",
        "correct_answer": "A",
        "explanation": "「〜てもらう」は誰かに自分のために何かしてもらうことを表します。「持ってもらえますか」で持つことをお願いしています。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "日本語を勉強する（　）、日本に来ました。",
        "option_a": "ために",
        "option_b": "ながら",
        "option_c": "から",
        "option_d": "ので",
        "correct_answer": "A",
        "explanation": "「〜ために」は目的を表します。「日本語を勉強するために来た」で日本語の勉強が来日の目的です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "電車が来（　）、急いでホームに走りました。",
        "option_a": "たので",
        "option_b": "るので",
        "option_c": "たのに",
        "option_d": "るのに",
        "correct_answer": "A",
        "explanation": "「〜たので」は過去の理由を表します。「電車が来たので急いだ」で電車の到着が急いだ理由です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "辞書を使っ（　）、調べてみました。",
        "option_a": "て",
        "option_b": "で",
        "option_c": "に",
        "option_d": "が",
        "correct_answer": "A",
        "explanation": "「辞書を使って調べる」で辞書を手段として使うことを表します。て形で手段や方法を示します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "この仕事は一人ではでき（　）。",
        "option_a": "ません",
        "option_b": "られません",
        "option_c": "ないです",
        "option_d": "Aも Cも正解",
        "correct_answer": "D",
        "explanation": "「できません」は「できる」の否定形です。「できないです」も同様に使えます。両方とも正しい表現です。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "部屋に入る（　）、電気をつけてください。",
        "option_a": "とき",
        "option_b": "ながら",
        "option_c": "てから",
        "option_d": "たり",
        "correct_answer": "A",
        "explanation": "「〜とき」は時を表します。「部屋に入るとき」で入る時点の行動を表します。",
        "source_url": "",
        "passage": "",
    },
    {
        "level": "N4",
        "question_type": "grammar",
        "question_text": "あの映画はとても感動的だっ（　）、泣いてしまいました。",
        "option_a": "たので",
        "option_b": "たのに",
        "option_c": "てから",
        "option_d": "ながら",
        "correct_answer": "A",
        "explanation": "「〜たので泣いた」は理由と結果の関係を表します。「感動的だったので」が泣いた理由です。",
        "source_url": "",
        "passage": "",
    },
]

N4_READING = [
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、田村さんはなぜ日本語を勉強し始めましたか。",
        "option_a": "日本の大学に入るため",
        "option_b": "日本のアニメが好きだから",
        "option_c": "仕事で日本語が必要になったから",
        "option_d": "日本人の友達ができたから",
        "correct_answer": "C",
        "explanation": "文章に「仕事で日本語が必要になり、勉強を始めました」と書いてあります。",
        "source_url": "",
        "passage": "田村さんは3年前から日本語を勉強しています。最初は仕事で日本語が必要になり、勉強を始めました。最初はとても難しかったですが、毎日少しずつ練習したおかげで、今では日常会話ができるようになりました。これからも勉強を続けて、日本語で仕事ができるようになりたいと思っています。",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この案内によると、申し込みはいつまでにしなければなりませんか。",
        "option_a": "3月15日",
        "option_b": "3月20日",
        "option_c": "3月25日",
        "option_d": "3月31日",
        "correct_answer": "B",
        "explanation": "案内に「申し込みは3月20日までにお願いします」と書いてあります。",
        "source_url": "",
        "passage": "日本語スピーチコンテストのお知らせ：日本語を学ぶ方を対象としたスピーチコンテストを4月10日に開催します。テーマは「私の夢」です。参加資格は日本語学習歴2年以上の方です。申し込みは3月20日までにお願いします。詳しくはウェブサイトをご覧ください。",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、佐藤さんが田舎に引っ越した一番の理由は何ですか。",
        "option_a": "自然が好きだから",
        "option_b": "仕事が変わったから",
        "option_c": "子供の教育のため",
        "option_d": "静かな環境で生活したかったから",
        "correct_answer": "D",
        "explanation": "「静かな環境で生活したいと思い、田舎に引っ越しました」と書いてあります。",
        "source_url": "",
        "passage": "佐藤さんはずっと東京に住んでいましたが、去年、田舎に引っ越しました。都会は便利ですが、毎日人が多くて疲れを感じていました。静かな環境で生活したいと思い、田舎に引っ越しました。今は自然に囲まれた生活を楽しんでいます。ただ、買い物が不便なのが少し困っています。",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、メールを送った人は何を頼んでいますか。",
        "option_a": "会議の場所を変えること",
        "option_b": "会議の時間を変えること",
        "option_c": "会議をキャンセルすること",
        "option_d": "会議に参加すること",
        "correct_answer": "B",
        "explanation": "「会議の時間を午後3時から午後4時に変えていただくことはできますか」と書いてあります。",
        "source_url": "",
        "passage": "件名：来週の会議について\n山田様\nお世話になっております。来週の会議についてご連絡します。急な用事ができてしまい、午後3時からの会議に間に合わない可能性があります。大変恐れ入りますが、会議の時間を午後3時から午後4時に変えていただくことはできますか。ご不便をおかけして申し訳ありません。田中",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、グリーンカフェの特徴として正しいものはどれですか。",
        "option_a": "24時間営業している",
        "option_b": "ペットと一緒に入れる",
        "option_c": "値段が安い",
        "option_d": "植物に囲まれた空間がある",
        "correct_answer": "D",
        "explanation": "「店内は植物に囲まれており、自然を感じながらゆっくり過ごせます」と書いてあります。",
        "source_url": "",
        "passage": "新しいカフェ「グリーンカフェ」が先月、駅前にオープンしました。店内は植物に囲まれており、自然を感じながらゆっくり過ごせます。コーヒーや紅茶のほか、ヘルシーな軽食も提供しています。営業時間は朝10時から夜9時までで、毎週火曜日が定休日です。ぜひ一度訪れてみてください。",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、木村さんのボランティア活動はどんな内容ですか。",
        "option_a": "子供に日本語を教える",
        "option_b": "老人ホームで音楽を演奏する",
        "option_c": "外国人の日本語学習を助ける",
        "option_d": "病院で患者の相談を聞く",
        "correct_answer": "C",
        "explanation": "「日本語を学ぶ外国人のサポートをするボランティアをしています」と書いてあります。",
        "source_url": "",
        "passage": "木村さんは月に2回、地域のボランティア活動に参加しています。日本語を学ぶ外国人のサポートをするボランティアをしています。日本語の練習相手になったり、生活上の困りごとを解決する手助けをしたりしています。この活動を通じて、自分も外国の文化を学ぶことができ、とても充実した時間を過ごしています。",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、スマートフォンを使いすぎることの問題は何ですか。",
        "option_a": "電池がなくなること",
        "option_b": "お金がかかること",
        "option_c": "睡眠に悪影響があること",
        "option_d": "友達が減ること",
        "correct_answer": "C",
        "explanation": "「特に寝る前にスマートフォンを見ると、睡眠の質が下がると言われています」と書いてあります。",
        "source_url": "",
        "passage": "最近、スマートフォンを使いすぎる人が増えています。便利なツールですが、使い過ぎると様々な問題が生じます。特に寝る前にスマートフォンを見ると、睡眠の質が下がると言われています。また、長時間画面を見続けると目が疲れ、肩や首にも負担がかかります。上手に使うことが大切です。",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、料理教室に申し込む方法はどれですか。",
        "option_a": "直接センターに行く",
        "option_b": "電話する",
        "option_c": "メールを送る",
        "option_d": "インターネットで申し込む",
        "correct_answer": "D",
        "explanation": "「参加希望の方はウェブサイトからお申し込みください」と書いてあります。",
        "source_url": "",
        "passage": "市民文化センターでは、毎月料理教室を開催しています。今月は和食の基本を学ぶコースです。講師は和食レストランで20年間料理を作ってきたシェフです。定員は15名で、材料費として2,000円が必要です。参加希望の方はウェブサイトからお申し込みください。締め切りは今月25日です。",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、山田さんが日記をつけ始めた理由は何ですか。",
        "option_a": "医者に勧められたから",
        "option_b": "友達に勧められたから",
        "option_c": "日本語の練習のため",
        "option_d": "記憶力を良くするため",
        "correct_answer": "B",
        "explanation": "「友達に勧められて、日記をつけ始めました」と書いてあります。",
        "source_url": "",
        "passage": "山田さんは3ヶ月前から日記をつけています。もともと日記は書かない人でしたが、友達に勧められて、日記をつけ始めました。毎日その日に起きたことや感じたことを書くことで、自分の気持ちを整理することができます。書くことで、以前より前向きな気持ちになれると山田さんは言っています。",
    },
    {
        "level": "N4",
        "question_type": "reading",
        "question_text": "この文章によると、春の日本で観光客に人気のことは何ですか。",
        "option_a": "スキーをすること",
        "option_b": "花火を見ること",
        "option_c": "花見をすること",
        "option_d": "温泉に入ること",
        "correct_answer": "C",
        "explanation": "「桜の花の下で食事を楽しむ花見は、春の日本の風物詩で、観光客にも人気があります」と書いてあります。",
        "source_url": "",
        "passage": "日本では春になると、桜の花が各地に咲き誇ります。桜の花の下で食事を楽しむ花見は、春の日本の風物詩で、観光客にも人気があります。東京では上野公園や新宿御苑が有名な花見スポットです。桜の開花時期は毎年異なりますが、東京では3月末から4月初めに見頃を迎えることが多いです。",
    },
]

N4_LISTENING = [
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、二人はどこに行くことになりましたか。",
        "option_a": "映画館",
        "option_b": "美術館",
        "option_c": "公園",
        "option_d": "レストラン",
        "correct_answer": "B",
        "explanation": "女の人が「美術館に行きましょう」と提案し、男の人が「いいですね、そうしましょう」と同意しています。",
        "source_url": "",
        "passage": "男：今週末、何か予定ありますか。\n女：特にないです。何かしませんか。\n男：映画はどうですか。新しい映画が公開されていますよ。\n女：映画は先週見たので、美術館に行きましょう。駅の近くに新しいのが開きましたよ。\n男：いいですね、そうしましょう。何時にしますか。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "このアナウンスによると、何のために列に並ぶ必要がありますか。",
        "option_a": "コンサートのチケットを買うため",
        "option_b": "サインをもらうため",
        "option_c": "写真を撮るため",
        "option_d": "入場するため",
        "correct_answer": "B",
        "explanation": "「サイン会に参加される方は、ここに列を作ってお待ちください」と言っています。",
        "source_url": "",
        "passage": "スタッフのアナウンス：お客様にご案内いたします。本日のサイン会は午後2時から始まります。サイン会に参加される方は、ここに列を作ってお待ちください。お一人様一冊のみサインをいたします。カメラでの撮影はご遠慮ください。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、女の人はなぜ遅刻しましたか。",
        "option_a": "道に迷ったから",
        "option_b": "電車が遅れたから",
        "option_c": "バスが来なかったから",
        "option_d": "寝坊したから",
        "correct_answer": "B",
        "explanation": "女の人は「電車が事故で止まってしまったんです」と言っています。",
        "source_url": "",
        "passage": "男：遅かったですね。何かあったんですか。\n女：すみません、遅れてしまいました。\n男：会議は始まってしまいましたよ。どうしたんですか。\n女：電車が事故で止まってしまったんです。駅で30分も待ちました。\n男：それは大変でしたね。では、会議室へ行きましょう。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、田中さんの試験の結果はどうでしたか。",
        "option_a": "合格した",
        "option_b": "不合格だった",
        "option_c": "まだ結果が出ていない",
        "option_d": "試験を受けなかった",
        "correct_answer": "A",
        "explanation": "田中さんが「合格しました！」と言っています。",
        "source_url": "",
        "passage": "女：田中さん、先日の試験どうでしたか。\n田中：合格しました！\n女：本当ですか。おめでとうございます！\n田中：ありがとうございます。何度も挑戦してやっとです。\n女：すごいですね。よかったですね。これからもがんばってください。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、男の人は何の薬が必要ですか。",
        "option_a": "頭痛薬",
        "option_b": "胃薬",
        "option_c": "風邪薬",
        "option_d": "目薬",
        "correct_answer": "C",
        "explanation": "男の人は「風邪薬をください」と言っています。",
        "source_url": "",
        "passage": "薬剤師：いらっしゃいませ。何かお探しですか。\n男：ええ、喉が痛くて、鼻水も出るんですが。\n薬剤師：熱はありますか。\n男：少しあります。37度5分くらいです。\n薬剤師：そうですか。どのような薬をお探しですか。\n男：風邪薬をください。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、女の人はこれから何をしますか。",
        "option_a": "仕事を続ける",
        "option_b": "友達に電話する",
        "option_c": "レストランに行く",
        "option_d": "早退する",
        "correct_answer": "D",
        "explanation": "「今日は早退してもいいですよ」と言われ、女の人は「ありがとうございます。では、お先に失礼します」と言っています。",
        "source_url": "",
        "passage": "上司：田中さん、顔色が悪いですよ。大丈夫ですか。\n田中：あ、実は少し頭痛がして。\n上司：無理しないで。今日は早退してもいいですよ。\n田中：でも、仕事が…\n上司：残りは明日やればいいです。お大事に。\n田中：ありがとうございます。では、お先に失礼します。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "このラジオ番組によると、明日の午後の天気はどうなりますか。",
        "option_a": "晴れる",
        "option_b": "曇りになる",
        "option_c": "雨が降る",
        "option_d": "雪が降る",
        "correct_answer": "C",
        "explanation": "「明日は午後から雨が降る見込みです」と言っています。",
        "source_url": "",
        "passage": "ラジオのアナウンサー：本日の天気予報をお伝えします。今日は全国的に晴れて、気持ちのいい天気です。しかし、明日は午後から雨が降る見込みです。特に夕方以降は雷を伴う激しい雨になる可能性がありますので、傘を忘れずにお出かけください。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、男の人はどんなアパートを探していますか。",
        "option_a": "駅に近くて、広いアパート",
        "option_b": "家賃が安くて、静かなアパート",
        "option_c": "新しくて、ペット可のアパート",
        "option_d": "駅から遠くても、広いアパート",
        "correct_answer": "B",
        "explanation": "「家賃が安くて静かな場所がいいです」と男の人が言っています。",
        "source_url": "",
        "passage": "不動産屋：どのようなアパートをお探しですか。\n男：そうですね、家賃が安くて静かな場所がいいです。\n不動産屋：駅からの距離はいかがですか。\n男：少し遠くてもかまいません。静かさが一番大切なので。\n不動産屋：わかりました。いくつかご紹介できる物件がございます。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、部長はなぜ会議に参加できませんか。",
        "option_a": "出張中だから",
        "option_b": "体調が悪いから",
        "option_c": "別の会議があるから",
        "option_d": "休日だから",
        "correct_answer": "A",
        "explanation": "「部長は今、大阪に出張中で参加できません」と言っています。",
        "source_url": "",
        "passage": "女：明日の会議、部長も参加しますか。\n男：いいえ、部長は今、大阪に出張中で参加できません。\n女：そうですか。では、誰が会議を進めるんですか。\n男：副部長の山田さんが代わりに進めます。\n女：わかりました。山田さんに事前に資料を送っておきます。",
    },
    {
        "level": "N4",
        "question_type": "listening",
        "is_active": False,
        "question_text": "この会話によると、二人は何を決めましたか。",
        "option_a": "旅行の場所",
        "option_b": "旅行の日程",
        "option_c": "旅行の費用",
        "option_d": "旅行のメンバー",
        "correct_answer": "A",
        "explanation": "「北海道に行くことにしましょう」と決め、二人が同意しています。",
        "source_url": "",
        "passage": "女：来月の旅行、どこにする？\n男：沖縄はどうかな。海がきれいだし。\n女：沖縄は夏に行ったから、今回は北の方がいいな。\n男：じゃあ、北海道は？食べ物もおいしいし。\n女：いいね。北海道に行くことにしましょう。\n男：決まりだね。じゃあ、宿を探そうか。",
    },
]


def get_n5_n4_questions() -> list[dict]:
    return (
        N5_VOCAB
        + N5_GRAMMAR
        + N5_READING
        + N5_LISTENING
        + N4_VOCAB
        + N4_GRAMMAR
        + N4_READING
        + N4_LISTENING
    )
